
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Notify07.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY

/// <summary>
/// Forever Handler for ActionCallback. An forever annotation indicates the closure will
/// be valid until the process terminates. Therefor the object will never be freed.
/// </summary>

public class ActionCallbackForeverHandler
{
    private Notify07.ActionCallback managedCallback;
    private GCHandle gch;

    public Notify07.Internal.ActionCallback NativeCallback;

    public ActionCallbackForeverHandler(Notify07.ActionCallback managed)
    {
        managedCallback = managed;
        gch = GCHandle.Alloc(this);
        
NativeCallback = (IntPtr notification, GLib.Internal.NonNullableUtf8StringHandle action, IntPtr userData) => {
    var notificationNative = (Notify07.Notification) GObject.Internal.InstanceWrapper.WrapHandle<Notify07.Notification>(notification, false);
var actionNative = action.ConvertToString();

    managedCallback(notificationNative, actionNative);

    
    
    
};
    }
}