
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Notify07.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY

/// <summary>
/// Call Handler for ActionCallback. A call annotation indicates the closure should
/// be valid for the duration of the call. This handler does not implement any special
/// memory management. 
/// </summary>

public class ActionCallbackCallHandler
{
    private Notify07.ActionCallback managedCallback;

    public Notify07.Internal.ActionCallback NativeCallback;

    public ActionCallbackCallHandler(Notify07.ActionCallback managed)
    {
        managedCallback = managed;
        
NativeCallback = (IntPtr notification, GLib.Internal.NonNullableUtf8StringHandle action, IntPtr userData) => {
    var notificationNative = (Notify07.Notification) GObject.Internal.InstanceWrapper.WrapHandle<Notify07.Notification>(notification, false);
var actionNative = action.ConvertToString();

    managedCallback(notificationNative, actionNative);

    
    
    
};
    }
}