
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace Notify07.Internal
{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public delegate void ActionCallback(IntPtr notification, GLib.Internal.NonNullableUtf8StringHandle action, IntPtr userData);
}