
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace Notify07.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY

internal static class Extensions
{
    public static T[] MarshalToStructure<T>(this IntPtr[] array)
    {
        var data = new T[array.Length];
    
        for(int i = 0; i < array.Length; i++)
            data[i] = Marshal.PtrToStructure<T>(array[i]) ?? throw new System.Exception("Cant marshal IntPtr[] because one element is not marshallable");

        return data;
    }
}