
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Notify07.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY

public static partial class Functions
{
    
/// <summary>
///Calls native function notify_get_app_icon.
///Version: 0.8.4
/// </summary>

/// <returns>Transfer ownership: None Nullable: False</returns>

[Version("0.8.4")]
[DllImport(ImportResolver.Library, EntryPoint = "notify_get_app_icon")]
public static extern GLib.Internal.NonNullableUtf8StringUnownedHandle GetAppIcon();

/// <summary>
///Calls native function notify_get_app_name.
/// </summary>

/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "notify_get_app_name")]
public static extern GLib.Internal.NonNullableUtf8StringUnownedHandle GetAppName();

/// <summary>
///Calls native function notify_get_server_caps.
/// </summary>

/// <returns>Transfer ownership: Full Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "notify_get_server_caps")]
public static extern GLib.Internal.ListOwnedHandle GetServerCaps();

/// <summary>
///Calls native function notify_get_server_info.
/// </summary>
/// <param name="retName">Transfer ownership: Full Nullable: False</param>
/// <param name="retVendor">Transfer ownership: Full Nullable: False</param>
/// <param name="retVersion">Transfer ownership: Full Nullable: False</param>
/// <param name="retSpecVersion">Transfer ownership: Full Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "notify_get_server_info")]
public static extern bool GetServerInfo(out GLib.Internal.NonNullableUtf8StringOwnedHandle retName, out GLib.Internal.NonNullableUtf8StringOwnedHandle retVendor, out GLib.Internal.NonNullableUtf8StringOwnedHandle retVersion, out GLib.Internal.NonNullableUtf8StringOwnedHandle retSpecVersion);

/// <summary>
///Calls native function notify_init.
/// </summary>
/// <param name="appName">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "notify_init")]
public static extern bool Init(GLib.Internal.NullableUtf8StringHandle appName);

/// <summary>
///Calls native function notify_is_initted.
/// </summary>

/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "notify_is_initted")]
public static extern bool IsInitted();

/// <summary>
///Calls native function notify_set_app_icon.
///Version: 0.8.4
/// </summary>
/// <param name="appIcon">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[Version("0.8.4")]
[DllImport(ImportResolver.Library, EntryPoint = "notify_set_app_icon")]
public static extern void SetAppIcon(GLib.Internal.NullableUtf8StringHandle appIcon);

/// <summary>
///Calls native function notify_set_app_name.
/// </summary>
/// <param name="appName">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "notify_set_app_name")]
public static extern void SetAppName(GLib.Internal.NonNullableUtf8StringHandle appName);

/// <summary>
///Calls native function notify_uninit.
/// </summary>

/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "notify_uninit")]
public static extern void Uninit();
}