
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Notify07.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY


[StructLayout(LayoutKind.Sequential)]
public partial struct NotificationClassData
{
    public delegate void ClosedCallback(IntPtr notification);

     public GObject.Internal.ObjectClassData ParentClass;
 public ClosedCallback Closed;
}