
using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Notify07.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY


public partial class NotificationClass
{
    
    
    
    
}