
using System;
using System.Diagnostics;
using System.Linq;
using System.Runtime.InteropServices;
using GObject;
using GObject.Internal;

namespace Notify07.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY

internal class TypeRegistration
{
    internal static void RegisterTypes()
    {
        Register<Notify07.Notification>(OSPlatform.Linux, OSPlatform.OSX, OSPlatform.Windows);

        

        

        
    }

    private static void Register<T>(params OSPlatform[] supportedPlatforms) where T : InstanceFactory, GTypeProvider
    {
         try
         {
            if(supportedPlatforms.Any(RuntimeInformation.IsOSPlatform))
                GObject.Internal.DynamicInstanceFactory.Register(T.GetGType(), T.Create);
         }
         catch(System.Exception e)
         {
             Debug.WriteLine($"Could not register type: {e.Message}");
         }
     }
}