
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Rsvg.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY

public static partial class Functions
{
    
/// <summary>
///Calls native function rsvg_cleanup.
///Version: 2.36
/// </summary>

/// <returns>Transfer ownership: None Nullable: False</returns>

[Version("2.36")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_cleanup")]
public static extern void Cleanup();

/// <summary>
///Calls native function rsvg_error_quark.
/// </summary>

/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "rsvg_error_quark")]
public static extern uint ErrorQuark();

/// <summary>
///Calls native function rsvg_init.
///Version: 2.9
/// </summary>

/// <returns>Transfer ownership: None Nullable: False</returns>

[Version("2.9")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_init")]
public static extern void Init();

/// <summary>
///Calls native function rsvg_pixbuf_from_file.
/// </summary>
/// <param name="filename">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: True</returns>


[DllImport(ImportResolver.Library, EntryPoint = "rsvg_pixbuf_from_file")]
public static extern IntPtr PixbufFromFile(GLib.Internal.NonNullableUtf8StringHandle filename, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native function rsvg_pixbuf_from_file_at_max_size.
/// </summary>
/// <param name="filename">Transfer ownership: None Nullable: False</param>
/// <param name="maxWidth">Transfer ownership: None Nullable: False</param>
/// <param name="maxHeight">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: True</returns>


[DllImport(ImportResolver.Library, EntryPoint = "rsvg_pixbuf_from_file_at_max_size")]
public static extern IntPtr PixbufFromFileAtMaxSize(GLib.Internal.NonNullableUtf8StringHandle filename, int maxWidth, int maxHeight, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native function rsvg_pixbuf_from_file_at_size.
/// </summary>
/// <param name="filename">Transfer ownership: None Nullable: False</param>
/// <param name="width">Transfer ownership: None Nullable: False</param>
/// <param name="height">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: True</returns>


[DllImport(ImportResolver.Library, EntryPoint = "rsvg_pixbuf_from_file_at_size")]
public static extern IntPtr PixbufFromFileAtSize(GLib.Internal.NonNullableUtf8StringHandle filename, int width, int height, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native function rsvg_pixbuf_from_file_at_zoom.
/// </summary>
/// <param name="filename">Transfer ownership: None Nullable: False</param>
/// <param name="xZoom">Transfer ownership: None Nullable: False</param>
/// <param name="yZoom">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: True</returns>


[DllImport(ImportResolver.Library, EntryPoint = "rsvg_pixbuf_from_file_at_zoom")]
public static extern IntPtr PixbufFromFileAtZoom(GLib.Internal.NonNullableUtf8StringHandle filename, double xZoom, double yZoom, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native function rsvg_pixbuf_from_file_at_zoom_with_max.
/// </summary>
/// <param name="filename">Transfer ownership: None Nullable: False</param>
/// <param name="xZoom">Transfer ownership: None Nullable: False</param>
/// <param name="yZoom">Transfer ownership: None Nullable: False</param>
/// <param name="maxWidth">Transfer ownership: None Nullable: False</param>
/// <param name="maxHeight">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: True</returns>


[DllImport(ImportResolver.Library, EntryPoint = "rsvg_pixbuf_from_file_at_zoom_with_max")]
public static extern IntPtr PixbufFromFileAtZoomWithMax(GLib.Internal.NonNullableUtf8StringHandle filename, double xZoom, double yZoom, int maxWidth, int maxHeight, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native function rsvg_set_default_dpi.
///Version: 2.8
/// </summary>
/// <param name="dpi">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[Version("2.8")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_set_default_dpi")]
public static extern void SetDefaultDpi(double dpi);

/// <summary>
///Calls native function rsvg_set_default_dpi_x_y.
///Version: 2.8
/// </summary>
/// <param name="dpiX">Transfer ownership: None Nullable: False</param>
/// <param name="dpiY">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[Version("2.8")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_set_default_dpi_x_y")]
public static extern void SetDefaultDpiXY(double dpiX, double dpiY);

/// <summary>
///Calls native function rsvg_term.
///Version: 2.9
/// </summary>

/// <returns>Transfer ownership: None Nullable: False</returns>

[Version("2.9")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_term")]
public static extern void Term();
}