
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Rsvg.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY


[StructLayout(LayoutKind.Sequential)]
public partial struct HandleData
{
     public GObject.Internal.ObjectData Parent;
[MarshalAs(UnmanagedType.ByValArray, SizeConst = 16)] public IntPtr[] AbiPadding;
}