
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Rsvg.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY


[StructLayout(LayoutKind.Sequential)]
public partial struct HandleClassData
{
    

     public GObject.Internal.ObjectClassData Parent;
[MarshalAs(UnmanagedType.ByValArray, SizeConst = 15)] public IntPtr[] AbiPadding;
}