
using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Rsvg.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY


public partial class Handle
{
    
/// <summary>
///Calls native function rsvg_handle_get_type.
/// </summary>

/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_get_type")]
public static extern nuint GetGType();
    
    
/// <summary>
///Calls native method rsvg_handle_close.
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_close")]
public static extern bool Close(IntPtr handle, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method rsvg_handle_free.
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_free")]
public static extern void Free(IntPtr handle);

/// <summary>
///Calls native method rsvg_handle_get_base_uri.
///Version: 2.8
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: False</returns>
[Version("2.8")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_get_base_uri")]
public static extern GLib.Internal.NonNullableUtf8StringUnownedHandle GetBaseUri(IntPtr handle);

/// <summary>
///Calls native method rsvg_handle_get_desc.
///Version: 2.4
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: True</returns>
[Version("2.4")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_get_desc")]
public static extern GLib.Internal.NullableUtf8StringUnownedHandle GetDesc(IntPtr handle);

/// <summary>
///Calls native method rsvg_handle_get_dimensions.
///Version: 2.14
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>
/// <param name="dimensionData">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>
[Version("2.14")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_get_dimensions")]
public static extern void GetDimensions(IntPtr handle, Rsvg.Internal.DimensionDataOwnedHandle dimensionData);

/// <summary>
///Calls native method rsvg_handle_get_dimensions_sub.
///Version: 2.22
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>
/// <param name="dimensionData">Transfer ownership: None Nullable: False</param>
/// <param name="id">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>
[Version("2.22")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_get_dimensions_sub")]
public static extern bool GetDimensionsSub(IntPtr handle, Rsvg.Internal.DimensionDataOwnedHandle dimensionData, GLib.Internal.NullableUtf8StringHandle id);

/// <summary>
///Calls native method rsvg_handle_get_geometry_for_element.
///Version: 2.46
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>
/// <param name="id">Transfer ownership: None Nullable: True</param>
/// <param name="outInkRect">Transfer ownership: None Nullable: False</param>
/// <param name="outLogicalRect">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>
[Version("2.46")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_get_geometry_for_element")]
public static extern bool GetGeometryForElement(IntPtr handle, GLib.Internal.NullableUtf8StringHandle id, Rsvg.Internal.RectangleOwnedHandle outInkRect, Rsvg.Internal.RectangleOwnedHandle outLogicalRect, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method rsvg_handle_get_geometry_for_layer.
///Version: 2.46
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>
/// <param name="id">Transfer ownership: None Nullable: True</param>
/// <param name="viewport">Transfer ownership: None Nullable: False</param>
/// <param name="outInkRect">Transfer ownership: None Nullable: False</param>
/// <param name="outLogicalRect">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>
[Version("2.46")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_get_geometry_for_layer")]
public static extern bool GetGeometryForLayer(IntPtr handle, GLib.Internal.NullableUtf8StringHandle id, Rsvg.Internal.RectangleHandle viewport, Rsvg.Internal.RectangleOwnedHandle outInkRect, Rsvg.Internal.RectangleOwnedHandle outLogicalRect, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method rsvg_handle_get_intrinsic_dimensions.
///Version: 2.46
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>
/// <param name="outHasWidth">Transfer ownership: Full Nullable: False</param>
/// <param name="outWidth">Transfer ownership: None Nullable: False</param>
/// <param name="outHasHeight">Transfer ownership: Full Nullable: False</param>
/// <param name="outHeight">Transfer ownership: None Nullable: False</param>
/// <param name="outHasViewbox">Transfer ownership: Full Nullable: False</param>
/// <param name="outViewbox">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>
[Version("2.46")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_get_intrinsic_dimensions")]
public static extern void GetIntrinsicDimensions(IntPtr handle, out bool outHasWidth, Rsvg.Internal.LengthOwnedHandle outWidth, out bool outHasHeight, Rsvg.Internal.LengthOwnedHandle outHeight, out bool outHasViewbox, Rsvg.Internal.RectangleOwnedHandle outViewbox);

/// <summary>
///Calls native method rsvg_handle_get_intrinsic_size_in_pixels.
///Version: 2.52
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>
/// <param name="outWidth">Transfer ownership: Full Nullable: False</param>
/// <param name="outHeight">Transfer ownership: Full Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>
[Version("2.52")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_get_intrinsic_size_in_pixels")]
public static extern bool GetIntrinsicSizeInPixels(IntPtr handle, out double outWidth, out double outHeight);

/// <summary>
///Calls native method rsvg_handle_get_metadata.
///Version: 2.9
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: True</returns>
[Version("2.9")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_get_metadata")]
public static extern GLib.Internal.NullableUtf8StringUnownedHandle GetMetadata(IntPtr handle);

/// <summary>
///Calls native method rsvg_handle_get_pixbuf.
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: Full Nullable: True</returns>

[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_get_pixbuf")]
public static extern IntPtr GetPixbuf(IntPtr handle);

/// <summary>
///Calls native method rsvg_handle_get_pixbuf_and_error.
///Version: 2.59
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: Full Nullable: True</returns>
[Version("2.59")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_get_pixbuf_and_error")]
public static extern IntPtr GetPixbufAndError(IntPtr handle, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method rsvg_handle_get_pixbuf_sub.
///Version: 2.14
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>
/// <param name="id">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: Full Nullable: True</returns>
[Version("2.14")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_get_pixbuf_sub")]
public static extern IntPtr GetPixbufSub(IntPtr handle, GLib.Internal.NullableUtf8StringHandle id);

/// <summary>
///Calls native method rsvg_handle_get_position_sub.
///Version: 2.22
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>
/// <param name="positionData">Transfer ownership: None Nullable: False</param>
/// <param name="id">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>
[Version("2.22")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_get_position_sub")]
public static extern bool GetPositionSub(IntPtr handle, Rsvg.Internal.PositionDataOwnedHandle positionData, GLib.Internal.NullableUtf8StringHandle id);

/// <summary>
///Calls native method rsvg_handle_get_title.
///Version: 2.4
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: True</returns>
[Version("2.4")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_get_title")]
public static extern GLib.Internal.NullableUtf8StringUnownedHandle GetTitle(IntPtr handle);

/// <summary>
///Calls native method rsvg_handle_has_sub.
///Version: 2.22
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>
/// <param name="id">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>
[Version("2.22")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_has_sub")]
public static extern bool HasSub(IntPtr handle, GLib.Internal.NonNullableUtf8StringHandle id);

/// <summary>
///Calls native method rsvg_handle_internal_set_testing.
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>
/// <param name="testing">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_internal_set_testing")]
public static extern void InternalSetTesting(IntPtr handle, bool testing);

/// <summary>
///Calls native method rsvg_handle_read_stream_sync.
///Version: 2.32
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>
/// <param name="stream">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>
[Version("2.32")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_read_stream_sync")]
public static extern bool ReadStreamSync(IntPtr handle, IntPtr stream, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method rsvg_handle_render_cairo.
///Version: 2.14
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>
/// <param name="cr">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>
[Version("2.14")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_render_cairo")]
public static extern bool RenderCairo(IntPtr handle, Cairo.Internal.ContextHandle cr);

/// <summary>
///Calls native method rsvg_handle_render_cairo_sub.
///Version: 2.14
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>
/// <param name="cr">Transfer ownership: None Nullable: False</param>
/// <param name="id">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>
[Version("2.14")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_render_cairo_sub")]
public static extern bool RenderCairoSub(IntPtr handle, Cairo.Internal.ContextHandle cr, GLib.Internal.NullableUtf8StringHandle id);

/// <summary>
///Calls native method rsvg_handle_render_document.
///Version: 2.46
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>
/// <param name="cr">Transfer ownership: None Nullable: False</param>
/// <param name="viewport">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>
[Version("2.46")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_render_document")]
public static extern bool RenderDocument(IntPtr handle, Cairo.Internal.ContextHandle cr, Rsvg.Internal.RectangleHandle viewport, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method rsvg_handle_render_element.
///Version: 2.46
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>
/// <param name="cr">Transfer ownership: None Nullable: False</param>
/// <param name="id">Transfer ownership: None Nullable: True</param>
/// <param name="elementViewport">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>
[Version("2.46")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_render_element")]
public static extern bool RenderElement(IntPtr handle, Cairo.Internal.ContextHandle cr, GLib.Internal.NullableUtf8StringHandle id, Rsvg.Internal.RectangleHandle elementViewport, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method rsvg_handle_render_layer.
///Version: 2.46
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>
/// <param name="cr">Transfer ownership: None Nullable: False</param>
/// <param name="id">Transfer ownership: None Nullable: True</param>
/// <param name="viewport">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>
[Version("2.46")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_render_layer")]
public static extern bool RenderLayer(IntPtr handle, Cairo.Internal.ContextHandle cr, GLib.Internal.NullableUtf8StringHandle id, Rsvg.Internal.RectangleHandle viewport, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method rsvg_handle_set_base_gfile.
///Version: 2.32
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>
/// <param name="baseFile">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>
[Version("2.32")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_set_base_gfile")]
public static extern void SetBaseGfile(IntPtr handle, IntPtr baseFile);

/// <summary>
///Calls native method rsvg_handle_set_base_uri.
///Version: 2.9
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>
/// <param name="baseUri">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>
[Version("2.9")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_set_base_uri")]
public static extern void SetBaseUri(IntPtr handle, GLib.Internal.NonNullableUtf8StringHandle baseUri);

/// <summary>
///Calls native method rsvg_handle_set_cancellable_for_rendering.
///Version: 2.59.0
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>
[Version("2.59.0")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_set_cancellable_for_rendering")]
public static extern void SetCancellableForRendering(IntPtr handle, IntPtr cancellable);

/// <summary>
///Calls native method rsvg_handle_set_dpi.
///Version: 2.8
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>
/// <param name="dpi">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>
[Version("2.8")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_set_dpi")]
public static extern void SetDpi(IntPtr handle, double dpi);

/// <summary>
///Calls native method rsvg_handle_set_dpi_x_y.
///Version: 2.8
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>
/// <param name="dpiX">Transfer ownership: None Nullable: False</param>
/// <param name="dpiY">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>
[Version("2.8")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_set_dpi_x_y")]
public static extern void SetDpiXY(IntPtr handle, double dpiX, double dpiY);

/// <summary>
///Calls native method rsvg_handle_set_size_callback.
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>
/// <param name="sizeFunc">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <param name="userDataDestroy">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_set_size_callback")]
public static extern void SetSizeCallback(IntPtr handle, Rsvg.Internal.SizeFunc sizeFunc, IntPtr userData, GLib.Internal.DestroyNotify userDataDestroy);

/// <summary>
///Calls native method rsvg_handle_set_stylesheet.
///Version: 2.48
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>
/// <param name="css">Transfer ownership: None Nullable: False</param>
/// <param name="cssLen">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>
[Version("2.48")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_set_stylesheet")]
public static extern bool SetStylesheet(IntPtr handle, ref byte css, nuint cssLen, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method rsvg_handle_write.
/// </summary>
/// <param name="handle">Transfer ownership: None Nullable: False</param>
/// <param name="buf">Transfer ownership: None Nullable: False</param>
/// <param name="count">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_write")]
public static extern bool Write(IntPtr handle, ref byte buf, nuint count, out GLib.Internal.ErrorOwnedHandle error);
    
/// <summary>
///Calls native constructor rsvg_handle_new.
/// </summary>

/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_new")]
public static extern IntPtr New();

/// <summary>
///Calls native constructor rsvg_handle_new_from_data.
///Version: 2.14
/// </summary>
/// <param name="data">Transfer ownership: None Nullable: False</param>
/// <param name="dataLen">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: True</returns>
[Version("2.14")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_new_from_data")]
public static extern IntPtr NewFromData(ref byte data, nuint dataLen, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native constructor rsvg_handle_new_from_file.
///Version: 2.14
/// </summary>
/// <param name="filename">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: True</returns>
[Version("2.14")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_new_from_file")]
public static extern IntPtr NewFromFile(GLib.Internal.NonNullableUtf8StringHandle filename, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native constructor rsvg_handle_new_from_gfile_sync.
///Version: 2.32
/// </summary>
/// <param name="file">Transfer ownership: None Nullable: False</param>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: Full Nullable: True</returns>
[Version("2.32")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_new_from_gfile_sync")]
public static extern IntPtr NewFromGfileSync(IntPtr file, Rsvg.HandleFlags flags, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native constructor rsvg_handle_new_from_stream_sync.
///Version: 2.32
/// </summary>
/// <param name="inputStream">Transfer ownership: None Nullable: False</param>
/// <param name="baseFile">Transfer ownership: None Nullable: True</param>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: Full Nullable: True</returns>
[Version("2.32")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_new_from_stream_sync")]
public static extern IntPtr NewFromStreamSync(IntPtr inputStream, IntPtr baseFile, Rsvg.HandleFlags flags, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native constructor rsvg_handle_new_with_flags.
///Version: 2.36
/// </summary>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>
[Version("2.36")]
[DllImport(ImportResolver.Library, EntryPoint = "rsvg_handle_new_with_flags")]
public static extern IntPtr NewWithFlags(Rsvg.HandleFlags flags);
}