
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Rsvg.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY


[StructLayout(LayoutKind.Sequential)]
public partial struct LengthData
{
    

     public double Length;
 public Rsvg.Unit Unit;
}