using System;
using GObject;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Rsvg.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY


public abstract class PositionDataHandle : SafeHandle
{    
    public sealed override bool IsInvalid => handle == IntPtr.Zero;

    protected PositionDataHandle(bool ownsHandle) : base(IntPtr.Zero, ownsHandle) { }

    public int GetX()
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    return Marshal.PtrToStructure<PositionDataData>(handle).X;
}
public void SetX(int value)
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    var data = Marshal.PtrToStructure<PositionDataData>(handle);
    data.X = value;
    Marshal.StructureToPtr(data, handle, false);
}

public int GetY()
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    return Marshal.PtrToStructure<PositionDataData>(handle).Y;
}
public void SetY(int value)
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    var data = Marshal.PtrToStructure<PositionDataData>(handle);
    data.Y = value;
    Marshal.StructureToPtr(data, handle, false);
}


    public bool Equals(PositionDataHandle? other)
    {
        if (ReferenceEquals(null, other))
            return false;

        if (ReferenceEquals(this, other))
            return true;

        return handle.Equals(other.handle);
    }

    public override bool Equals(object? obj)
    {
        return ReferenceEquals(this, obj) || obj is PositionDataHandle other && Equals(other);
    }

    public override int GetHashCode()
    {
        return handle.GetHashCode();
    }
}

public class PositionDataUnownedHandle : PositionDataHandle
{
    private static PositionDataUnownedHandle? nullHandle;
    public static PositionDataUnownedHandle NullHandle => nullHandle ??= new PositionDataUnownedHandle();

    /// <summary>
    /// Creates a new instance of PositionDataUnownedHandle. Used automatically by PInvoke.
    /// </summary>
    internal PositionDataUnownedHandle() : base(false) { }

    /// <summary>
    /// Creates a new instance of PositionDataOwnedHandle. Assumes that the given pointer is unowned by the runtime.
    /// </summary>
    public PositionDataUnownedHandle(IntPtr ptr) : base(false)
    {
        SetHandle(ptr);
    }

    public PositionDataOwnedHandle Copy()
    {
        var size = Marshal.SizeOf<PositionDataData>();
        var ptr = GLib.Functions.Memdup2(handle,(nuint) size);
            
        return new PositionDataOwnedHandle(ptr);
    }

    protected override bool ReleaseHandle()
    {
        throw new System.Exception("UnownedHandle must not be freed");
    }
}

public class PositionDataOwnedHandle : PositionDataHandle
{
    /// <summary>
    /// Creates a new instance of PositionDataOwnedHandle. Used automatically by PInvoke.
    /// </summary>
    internal PositionDataOwnedHandle() : base(true) { }

    /// <summary>
    /// Creates a new instance of PositionDataOwnedHandle. Assumes that the given pointer is owned by the runtime.
    /// </summary>
    public PositionDataOwnedHandle(IntPtr ptr) : base(true)
    {
        SetHandle(ptr);
    }

    /// <summary>
    /// Creates a new owned Handle
    /// </summary>
    public static PositionDataOwnedHandle Create()
    {
        var size = Marshal.SizeOf<PositionDataData>();
        var ptr = GLib.Functions.Malloc((nuint)size);
       
        var str = new PositionDataData();
        Marshal.StructureToPtr(str, ptr, false);
            
        return new PositionDataOwnedHandle(ptr);
    }

    public unsafe void CopyTo(IntPtr ptr)
    {
        var data = Marshal.PtrToStructure<PositionDataData>(handle);
        Marshal.StructureToPtr(data, ptr, false);
    }

    public PositionDataUnownedHandle UnownedCopy()
    {
        var size = Marshal.SizeOf<PositionDataData>();
        var ptr = GLib.Functions.Memdup2(handle,(nuint) size);
            
        return new PositionDataUnownedHandle(ptr);
    }

    protected override bool ReleaseHandle()
    {
        GLib.Functions.Free(handle);
        return true;
    }
}

public abstract class PositionDataArrayHandle : SafeHandle
{
    public sealed override bool IsInvalid => handle == IntPtr.Zero;

    protected PositionDataArrayHandle(bool ownsHandle) : base(IntPtr.Zero, ownsHandle) { }
}

public class PositionDataArrayUnownedHandle : PositionDataArrayHandle
{
    private static PositionDataArrayUnownedHandle? nullHandle;
    public static PositionDataArrayUnownedHandle NullHandle => nullHandle ??= new PositionDataArrayUnownedHandle();
    
    private int length;

    /// <summary>
    /// Creates a new instance of PositionDataArrayUnownedHandle. Used automatically by PInvoke.
    /// </summary>
    internal PositionDataArrayUnownedHandle() : base(false) { }
    
    public PositionDataArrayUnownedHandle(IntPtr ptr, int length) : base(false)
    {
        this.length = length;
        SetHandle(ptr);
    }

    public Rsvg.PositionData[] ToArray(int length)
    {
        return ToNullableArray(length) ?? throw new InvalidOperationException("Handle is invalid");
    }

    public Rsvg.PositionData[]? ToNullableArray(int length)
    {
        if (IsInvalid)
            return null;
        
        var data = new Rsvg.PositionData[length];
        var currentHandle = handle;
        for(int i = 0; i < length; i++)
        {
            var ownedHandle = new Rsvg.Internal.PositionDataUnownedHandle(currentHandle).Copy();
            data[i] = new Rsvg.PositionData(ownedHandle);
            currentHandle += Marshal.SizeOf<Rsvg.Internal.PositionDataData>();
        }

        return data;
    }

    protected override bool ReleaseHandle()
    {
        throw new System.Exception("UnownedHandle must not be freed");
    }
}

public class PositionDataArrayOwnedHandle : PositionDataArrayHandle
{
    
    //This has no constructor without parameters as we can't supply a length to an array via pinvoke.
    //The length would need to be set manually and the instance be freed via glib.

    private PositionDataArrayOwnedHandle(IntPtr ptr) : base(true)
    {
        SetHandle(ptr);
    }

    public static PositionDataArrayOwnedHandle Create(Rsvg.PositionData[] data)
    {
        var size = Marshal.SizeOf<Rsvg.Internal.PositionDataData>();
        var ptr = Marshal.AllocHGlobal(size * data.Length);
        var current = ptr;
        for (int i = 0; i < data.Length; i++)
        {
            var structure = Marshal.PtrToStructure<Rsvg.Internal.PositionDataData>(data[i].Handle.DangerousGetHandle());
            Marshal.StructureToPtr(structure, current, false);
            current += size;
        }
        
        return new PositionDataArrayOwnedHandle(ptr);
    }
    
    protected override bool ReleaseHandle()
    {
        Marshal.FreeHGlobal(handle);
        return true;
    }
}