using System;
using GObject;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Rsvg.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY


public abstract class RectangleHandle : SafeHandle
{    
    public sealed override bool IsInvalid => handle == IntPtr.Zero;

    protected RectangleHandle(bool ownsHandle) : base(IntPtr.Zero, ownsHandle) { }

    public double GetX()
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    return Marshal.PtrToStructure<RectangleData>(handle).X;
}
public void SetX(double value)
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    var data = Marshal.PtrToStructure<RectangleData>(handle);
    data.X = value;
    Marshal.StructureToPtr(data, handle, false);
}

public double GetY()
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    return Marshal.PtrToStructure<RectangleData>(handle).Y;
}
public void SetY(double value)
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    var data = Marshal.PtrToStructure<RectangleData>(handle);
    data.Y = value;
    Marshal.StructureToPtr(data, handle, false);
}

public double GetWidth()
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    return Marshal.PtrToStructure<RectangleData>(handle).Width;
}
public void SetWidth(double value)
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    var data = Marshal.PtrToStructure<RectangleData>(handle);
    data.Width = value;
    Marshal.StructureToPtr(data, handle, false);
}

public double GetHeight()
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    return Marshal.PtrToStructure<RectangleData>(handle).Height;
}
public void SetHeight(double value)
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    var data = Marshal.PtrToStructure<RectangleData>(handle);
    data.Height = value;
    Marshal.StructureToPtr(data, handle, false);
}


    public bool Equals(RectangleHandle? other)
    {
        if (ReferenceEquals(null, other))
            return false;

        if (ReferenceEquals(this, other))
            return true;

        return handle.Equals(other.handle);
    }

    public override bool Equals(object? obj)
    {
        return ReferenceEquals(this, obj) || obj is RectangleHandle other && Equals(other);
    }

    public override int GetHashCode()
    {
        return handle.GetHashCode();
    }
}

public class RectangleUnownedHandle : RectangleHandle
{
    private static RectangleUnownedHandle? nullHandle;
    public static RectangleUnownedHandle NullHandle => nullHandle ??= new RectangleUnownedHandle();

    /// <summary>
    /// Creates a new instance of RectangleUnownedHandle. Used automatically by PInvoke.
    /// </summary>
    internal RectangleUnownedHandle() : base(false) { }

    /// <summary>
    /// Creates a new instance of RectangleOwnedHandle. Assumes that the given pointer is unowned by the runtime.
    /// </summary>
    public RectangleUnownedHandle(IntPtr ptr) : base(false)
    {
        SetHandle(ptr);
    }

    public RectangleOwnedHandle Copy()
    {
        var size = Marshal.SizeOf<RectangleData>();
        var ptr = GLib.Functions.Memdup2(handle,(nuint) size);
            
        return new RectangleOwnedHandle(ptr);
    }

    protected override bool ReleaseHandle()
    {
        throw new System.Exception("UnownedHandle must not be freed");
    }
}

public class RectangleOwnedHandle : RectangleHandle
{
    /// <summary>
    /// Creates a new instance of RectangleOwnedHandle. Used automatically by PInvoke.
    /// </summary>
    internal RectangleOwnedHandle() : base(true) { }

    /// <summary>
    /// Creates a new instance of RectangleOwnedHandle. Assumes that the given pointer is owned by the runtime.
    /// </summary>
    public RectangleOwnedHandle(IntPtr ptr) : base(true)
    {
        SetHandle(ptr);
    }

    /// <summary>
    /// Creates a new owned Handle
    /// </summary>
    public static RectangleOwnedHandle Create()
    {
        var size = Marshal.SizeOf<RectangleData>();
        var ptr = GLib.Functions.Malloc((nuint)size);
       
        var str = new RectangleData();
        Marshal.StructureToPtr(str, ptr, false);
            
        return new RectangleOwnedHandle(ptr);
    }

    public unsafe void CopyTo(IntPtr ptr)
    {
        var data = Marshal.PtrToStructure<RectangleData>(handle);
        Marshal.StructureToPtr(data, ptr, false);
    }

    public RectangleUnownedHandle UnownedCopy()
    {
        var size = Marshal.SizeOf<RectangleData>();
        var ptr = GLib.Functions.Memdup2(handle,(nuint) size);
            
        return new RectangleUnownedHandle(ptr);
    }

    protected override bool ReleaseHandle()
    {
        GLib.Functions.Free(handle);
        return true;
    }
}

public abstract class RectangleArrayHandle : SafeHandle
{
    public sealed override bool IsInvalid => handle == IntPtr.Zero;

    protected RectangleArrayHandle(bool ownsHandle) : base(IntPtr.Zero, ownsHandle) { }
}

public class RectangleArrayUnownedHandle : RectangleArrayHandle
{
    private static RectangleArrayUnownedHandle? nullHandle;
    public static RectangleArrayUnownedHandle NullHandle => nullHandle ??= new RectangleArrayUnownedHandle();
    
    private int length;

    /// <summary>
    /// Creates a new instance of RectangleArrayUnownedHandle. Used automatically by PInvoke.
    /// </summary>
    internal RectangleArrayUnownedHandle() : base(false) { }
    
    public RectangleArrayUnownedHandle(IntPtr ptr, int length) : base(false)
    {
        this.length = length;
        SetHandle(ptr);
    }

    public Rsvg.Rectangle[] ToArray(int length)
    {
        return ToNullableArray(length) ?? throw new InvalidOperationException("Handle is invalid");
    }

    public Rsvg.Rectangle[]? ToNullableArray(int length)
    {
        if (IsInvalid)
            return null;
        
        var data = new Rsvg.Rectangle[length];
        var currentHandle = handle;
        for(int i = 0; i < length; i++)
        {
            var ownedHandle = new Rsvg.Internal.RectangleUnownedHandle(currentHandle).Copy();
            data[i] = new Rsvg.Rectangle(ownedHandle);
            currentHandle += Marshal.SizeOf<Rsvg.Internal.RectangleData>();
        }

        return data;
    }

    protected override bool ReleaseHandle()
    {
        throw new System.Exception("UnownedHandle must not be freed");
    }
}

public class RectangleArrayOwnedHandle : RectangleArrayHandle
{
    
    //This has no constructor without parameters as we can't supply a length to an array via pinvoke.
    //The length would need to be set manually and the instance be freed via glib.

    private RectangleArrayOwnedHandle(IntPtr ptr) : base(true)
    {
        SetHandle(ptr);
    }

    public static RectangleArrayOwnedHandle Create(Rsvg.Rectangle[] data)
    {
        var size = Marshal.SizeOf<Rsvg.Internal.RectangleData>();
        var ptr = Marshal.AllocHGlobal(size * data.Length);
        var current = ptr;
        for (int i = 0; i < data.Length; i++)
        {
            var structure = Marshal.PtrToStructure<Rsvg.Internal.RectangleData>(data[i].Handle.DangerousGetHandle());
            Marshal.StructureToPtr(structure, current, false);
            current += size;
        }
        
        return new RectangleArrayOwnedHandle(ptr);
    }
    
    protected override bool ReleaseHandle()
    {
        Marshal.FreeHGlobal(handle);
        return true;
    }
}