
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Rsvg.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY

/// <summary>
/// Call Handler for SizeFunc. A call annotation indicates the closure should
/// be valid for the duration of the call. This handler does not implement any special
/// memory management. 
/// </summary>

public class SizeFuncCallHandler
{
    private Rsvg.SizeFunc managedCallback;

    public Rsvg.Internal.SizeFunc NativeCallback;

    public SizeFuncCallHandler(Rsvg.SizeFunc managed)
    {
        managedCallback = managed;
        
NativeCallback = (out int width, out int height, IntPtr userData) => {
    


    managedCallback(out width, out height);

    
    
    
};
    }
}