
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace Rsvg.Internal
{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public delegate void SizeFunc(out int width, out int height, IntPtr userData);
}