
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Rsvg.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY

/// <summary>
/// Async Handler for SizeFunc. An async annotation indicates the closure will
/// be called precisely once, after which it is then available for garbage collection.
/// </summary>

public class SizeFuncAsyncHandler
{
    private Rsvg.SizeFunc managedCallback;
    private GCHandle gch;

    public Rsvg.Internal.SizeFunc NativeCallback;

    public SizeFuncAsyncHandler(Rsvg.SizeFunc managed)
    {
        managedCallback = managed;
        gch = GCHandle.Alloc(this);
        
NativeCallback = (out int width, out int height, IntPtr userData) => {
    


    managedCallback(out width, out height);

    
    gch.Free();
    
};
    }
}