
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Rsvg.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY

/// <summary>
/// Forever Handler for SizeFunc. An forever annotation indicates the closure will
/// be valid until the process terminates. Therefor the object will never be freed.
/// </summary>

public class SizeFuncForeverHandler
{
    private Rsvg.SizeFunc managedCallback;
    private GCHandle gch;

    public Rsvg.Internal.SizeFunc NativeCallback;

    public SizeFuncForeverHandler(Rsvg.SizeFunc managed)
    {
        managedCallback = managed;
        gch = GCHandle.Alloc(this);
        
NativeCallback = (out int width, out int height, IntPtr userData) => {
    


    managedCallback(out width, out height);

    
    
    
};
    }
}