
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace Notify07;

// AUTOGENERATED FILE - DO NOT MODIFY

public delegate void ActionCallback(Notify07.Notification notification, string action);