
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Notify07;

// AUTOGENERATED FILE - DO NOT MODIFY


public enum ClosedReason : int
{
    Unset = -1,
Expired = 1,
Dismissed = 2,
ApiRequest = 3,
Undefiend = 4,
}