
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Notify07;

// AUTOGENERATED FILE - DO NOT MODIFY

public partial class Constants
{
    

public const int EXPIRES_DEFAULT = -1;


public const int EXPIRES_NEVER = 0;


public const int VERSION_MAJOR = 0;


public const int VERSION_MICRO = 6;


public const int VERSION_MINOR = 8;
}