
using System;
using System.Linq;
using System.Runtime.InteropServices;

#nullable enable

namespace Notify07;

// AUTOGENERATED FILE - DO NOT MODIFY

public static partial class Functions
{
    
[Version("0.8.4")]
public static string GetAppIcon()
{
    
    var resultGetAppIcon = Notify07.Internal.Functions.GetAppIcon();

    
    
    return resultGetAppIcon.ConvertToString();
}


public static string GetAppName()
{
    
    var resultGetAppName = Notify07.Internal.Functions.GetAppName();

    
    
    return resultGetAppName.ConvertToString();
}


public static GLib.List GetServerCaps()
{
    
    var resultGetServerCaps = Notify07.Internal.Functions.GetServerCaps();

    
    
    return new GLib.List(resultGetServerCaps);
}


public static bool GetServerInfo(out string retName, out string retVendor, out string retVersion, out string retSpecVersion)
{
    
    var resultGetServerInfo = Notify07.Internal.Functions.GetServerInfo(out var retNameNative, out var retVendorNative, out var retVersionNative, out var retSpecVersionNative);

    retName = retNameNative.ConvertToString();
retNameNative.Dispose();
retVendor = retVendorNative.ConvertToString();
retVendorNative.Dispose();
retVersion = retVersionNative.ConvertToString();
retVersionNative.Dispose();
retSpecVersion = retSpecVersionNative.ConvertToString();
retSpecVersionNative.Dispose();
    
    return resultGetServerInfo;
}


public static bool Init(string? appName)
{
    using var appNameNative = GLib.Internal.NullableUtf8StringOwnedHandle.Create(appName);
    var resultInit = Notify07.Internal.Functions.Init(appNameNative);

    
    
    return resultInit;
}


public static bool IsInitted()
{
    
    var resultIsInitted = Notify07.Internal.Functions.IsInitted();

    
    
    return resultIsInitted;
}

[Version("0.8.4")]
public static void SetAppIcon(string? appIcon)
{
    using var appIconNative = GLib.Internal.NullableUtf8StringOwnedHandle.Create(appIcon);
    Notify07.Internal.Functions.SetAppIcon(appIconNative);

    
    
    
}


public static void SetAppName(string appName)
{
    using var appNameNative = GLib.Internal.NonNullableUtf8StringOwnedHandle.Create(appName);
    Notify07.Internal.Functions.SetAppName(appNameNative);

    
    
    
}


public static void Uninit()
{
    
    Notify07.Internal.Functions.Uninit();

    
    
    
}
}