
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Notify07;

// AUTOGENERATED FILE - DO NOT MODIFY


public sealed partial class NotificationClass
{
    public Notify07.Internal.NotificationClassOwnedHandle Handle { get; }

    public NotificationClass(Notify07.Internal.NotificationClassOwnedHandle handle)
    {
        Handle = handle;
    }

    public NotificationClass() : this(Notify07.Internal.NotificationClassOwnedHandle.Create())
    {
    }

    

    


    

    

    public bool Equals(NotificationClass? other)
    {
        if (ReferenceEquals(null, other))
            return false;

        if (ReferenceEquals(this, other))
            return true;

        return Handle.Equals(other.Handle);
    }

    public override bool Equals(object? obj)
    {
        return ReferenceEquals(this, obj) || obj is NotificationClass other && Equals(other);
    }

    public override int GetHashCode()
    {
        return Handle.GetHashCode();
    }
}