
using System;
using GObject;
using System.Runtime.InteropServices;

#nullable enable

namespace Notify07
{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class Notification
    {
        
#region OnClosed


/// <summary>
/// Signal Descriptor for OnClosed.
/// </summary>
public static readonly Signal<Notification> ClosedSignal = new (
    unmanagedName: "closed",
    managedName: nameof(OnClosed)
);

public event SignalHandler<Notification> OnClosed
{
    add => ClosedSignal.Connect(this, value);
    remove => ClosedSignal.Disconnect(this, value);
}
#endregion

    }
}