
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Notify07;

// AUTOGENERATED FILE - DO NOT MODIFY


[GObject.Handle<Notify07.Internal.NotificationHandle>]
public partial class Notification(Notify07.Internal.NotificationHandle handle) : GObject.Object(handle)
{
       public Notification(params GObject.ConstructArgument[] constructArguments) : this(Notify07.Internal.NotificationHandle.For<Notification>(constructArguments)) { }
}