
using System;
using System.Linq;
using GObject;
using System.Runtime.InteropServices;

#nullable enable

namespace Notify07;

// AUTOGENERATED FILE - DO NOT MODIFY

public partial class Notification : GObject.GTypeProvider, GObject.InstanceFactory
{

    public static new GObject.Type GetGType()
    {
        return Notify07.Internal.Notification.GetGType();
    }

    static object GObject.InstanceFactory.Create(IntPtr handle, bool ownsHandle)
    {
        return CreateIntern(handle, ownsHandle);
    }

    private static Notification CreateIntern(IntPtr handle, bool ownsHandle)
    {
        return new Notification(new Notify07.Internal.NotificationHandle(handle, ownsHandle));
    }

    
}