
using System;
using System.Linq;
using GObject;
using System.Runtime.InteropServices;

#nullable enable

namespace Notify07;

// AUTOGENERATED FILE - DO NOT MODIFY

public partial class Notification
{
    

public static Notification New(string summary, string? body, string? icon)
{
    using var summaryNative = GLib.Internal.NonNullableUtf8StringOwnedHandle.Create(summary);
using var bodyNative = GLib.Internal.NullableUtf8StringOwnedHandle.Create(body);
using var iconNative = GLib.Internal.NullableUtf8StringOwnedHandle.Create(icon);
    var notificationHandle = Internal.Notification.New(summaryNative, bodyNative, iconNative);
return Notify07.Notification.CreateIntern(notificationHandle, true);

}
}