
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Notify07;

// AUTOGENERATED FILE - DO NOT MODIFY


public enum Urgency : int
{
    Low = 0,
Normal = 1,
Critical = 2,
}