
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY


[StructLayout(LayoutKind.Sequential)]
public partial struct BackendInterfaceData
{
    public delegate void EnsureForFlagsCallback(IntPtr self, Secret.BackendFlags flags, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);
public delegate bool EnsureForFlagsFinishCallback(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);
public delegate void StoreCallback(IntPtr self, IntPtr schema, IntPtr attributes, GLib.Internal.NonNullableUtf8StringHandle collection, GLib.Internal.NonNullableUtf8StringHandle label, IntPtr value, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);
public delegate bool StoreFinishCallback(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);
public delegate void LookupCallback(IntPtr self, IntPtr schema, IntPtr attributes, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);
public delegate IntPtr LookupFinishCallback(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);
public delegate void ClearCallback(IntPtr self, IntPtr schema, IntPtr attributes, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);
public delegate bool ClearFinishCallback(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);
public delegate void SearchCallback(IntPtr self, IntPtr schema, IntPtr attributes, Secret.SearchFlags flags, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);
public delegate IntPtr SearchFinishCallback(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

     public GObject.Internal.TypeInterfaceData ParentIface;
 public EnsureForFlagsCallback EnsureForFlags;
 public EnsureForFlagsFinishCallback EnsureForFlagsFinish;
 public StoreCallback Store;
 public StoreFinishCallback StoreFinish;
 public LookupCallback Lookup;
 public LookupFinishCallback LookupFinish;
 public ClearCallback Clear;
 public ClearFinishCallback ClearFinish;
 public SearchCallback Search;
 public SearchFinishCallback SearchFinish;
}