
using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY


public partial class Backend
{
    
/// <summary>
///Calls native function secret_backend_get_type.
/// </summary>

/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_backend_get_type")]
public static extern nuint GetGType();
    
/// <summary>
///Calls native function secret_backend_get.
///Version: 0.19.0
/// </summary>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[Version("0.19.0")]
[DllImport(ImportResolver.Library, EntryPoint = "secret_backend_get")]
public static extern void Get(Secret.BackendFlags flags, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native function secret_backend_get_finish.
///Version: 0.19.0
/// </summary>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[Version("0.19.0")]
[DllImport(ImportResolver.Library, EntryPoint = "secret_backend_get_finish")]
public static extern IntPtr GetFinish(IntPtr result, out GLib.Internal.ErrorOwnedHandle error);
    
}