
using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY


public partial class Collection
{
    
/// <summary>
///Calls native function secret_collection_get_type.
/// </summary>

/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_get_type")]
public static extern nuint GetGType();
    
/// <summary>
///Calls native function secret_collection_create.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: True</param>
/// <param name="label">Transfer ownership: None Nullable: False</param>
/// <param name="alias">Transfer ownership: None Nullable: True</param>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_create")]
public static extern void Create(IntPtr service, GLib.Internal.NonNullableUtf8StringHandle label, GLib.Internal.NullableUtf8StringHandle alias, Secret.CollectionCreateFlags flags, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native function secret_collection_create_finish.
/// </summary>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_create_finish")]
public static extern IntPtr CreateFinish(IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native function secret_collection_create_sync.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: True</param>
/// <param name="label">Transfer ownership: None Nullable: False</param>
/// <param name="alias">Transfer ownership: None Nullable: True</param>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_create_sync")]
public static extern IntPtr CreateSync(IntPtr service, GLib.Internal.NonNullableUtf8StringHandle label, GLib.Internal.NullableUtf8StringHandle alias, Secret.CollectionCreateFlags flags, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native function secret_collection_for_alias.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: True</param>
/// <param name="alias">Transfer ownership: None Nullable: False</param>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_for_alias")]
public static extern void ForAlias(IntPtr service, GLib.Internal.NonNullableUtf8StringHandle alias, Secret.CollectionFlags flags, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native function secret_collection_for_alias_finish.
/// </summary>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: True</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_for_alias_finish")]
public static extern IntPtr ForAliasFinish(IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native function secret_collection_for_alias_sync.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: True</param>
/// <param name="alias">Transfer ownership: None Nullable: False</param>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: Full Nullable: True</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_for_alias_sync")]
public static extern IntPtr ForAliasSync(IntPtr service, GLib.Internal.NonNullableUtf8StringHandle alias, Secret.CollectionFlags flags, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native function secret_collection_new_for_dbus_path.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: True</param>
/// <param name="collectionPath">Transfer ownership: None Nullable: False</param>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_new_for_dbus_path")]
public static extern void NewForDbusPath(IntPtr service, GLib.Internal.NonNullableUtf8StringHandle collectionPath, Secret.CollectionFlags flags, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);
    
/// <summary>
///Calls native method secret_collection_delete.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_delete")]
public static extern void Delete(IntPtr self, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_collection_delete_finish.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_delete_finish")]
public static extern bool DeleteFinish(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_collection_delete_sync.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_delete_sync")]
public static extern bool DeleteSync(IntPtr self, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_collection_get_created.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_get_created")]
public static extern ulong GetCreated(IntPtr self);

/// <summary>
///Calls native method secret_collection_get_flags.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_get_flags")]
public static extern Secret.CollectionFlags GetFlags(IntPtr self);

/// <summary>
///Calls native method secret_collection_get_items.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_get_items")]
public static extern GLib.Internal.ListOwnedHandle GetItems(IntPtr self);

/// <summary>
///Calls native method secret_collection_get_label.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_get_label")]
public static extern GLib.Internal.NonNullableUtf8StringOwnedHandle GetLabel(IntPtr self);

/// <summary>
///Calls native method secret_collection_get_locked.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_get_locked")]
public static extern bool GetLocked(IntPtr self);

/// <summary>
///Calls native method secret_collection_get_modified.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_get_modified")]
public static extern ulong GetModified(IntPtr self);

/// <summary>
///Calls native method secret_collection_get_service.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_get_service")]
public static extern IntPtr GetService(IntPtr self);

/// <summary>
///Calls native method secret_collection_load_items.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_load_items")]
public static extern void LoadItems(IntPtr self, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_collection_load_items_finish.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_load_items_finish")]
public static extern bool LoadItemsFinish(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_collection_load_items_sync.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_load_items_sync")]
public static extern bool LoadItemsSync(IntPtr self, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_collection_refresh.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_refresh")]
public static extern void Refresh(IntPtr self);

/// <summary>
///Calls native method secret_collection_search.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: None Nullable: False</param>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_search")]
public static extern void Search(IntPtr self, Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableHandle attributes, Secret.SearchFlags flags, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_collection_search_finish.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_search_finish")]
public static extern GLib.Internal.ListOwnedHandle SearchFinish(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_collection_search_for_dbus_paths.
/// </summary>
/// <param name="collection">Transfer ownership: None Nullable: False</param>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_search_for_dbus_paths")]
public static extern void SearchForDbusPaths(IntPtr collection, Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableHandle attributes, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_collection_search_for_dbus_paths_finish.
/// </summary>
/// <param name="collection">Transfer ownership: None Nullable: False</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_search_for_dbus_paths_finish")]
public static extern GLib.Internal.Utf8StringArrayNullTerminatedOwnedHandle SearchForDbusPathsFinish(IntPtr collection, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_collection_search_for_dbus_paths_sync.
/// </summary>
/// <param name="collection">Transfer ownership: None Nullable: False</param>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_search_for_dbus_paths_sync")]
public static extern GLib.Internal.Utf8StringArrayNullTerminatedOwnedHandle SearchForDbusPathsSync(IntPtr collection, Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableHandle attributes, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_collection_search_sync.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: None Nullable: False</param>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_search_sync")]
public static extern GLib.Internal.ListOwnedHandle SearchSync(IntPtr self, Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableHandle attributes, Secret.SearchFlags flags, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_collection_set_label.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="label">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_set_label")]
public static extern void SetLabel(IntPtr self, GLib.Internal.NonNullableUtf8StringHandle label, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_collection_set_label_finish.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_set_label_finish")]
public static extern bool SetLabelFinish(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_collection_set_label_sync.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="label">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_set_label_sync")]
public static extern bool SetLabelSync(IntPtr self, GLib.Internal.NonNullableUtf8StringHandle label, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);
    
/// <summary>
///Calls native constructor secret_collection_new_for_dbus_path_finish.
/// </summary>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_new_for_dbus_path_finish")]
public static extern IntPtr NewForDbusPathFinish(IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native constructor secret_collection_new_for_dbus_path_sync.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: True</param>
/// <param name="collectionPath">Transfer ownership: None Nullable: False</param>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_collection_new_for_dbus_path_sync")]
public static extern IntPtr NewForDbusPathSync(IntPtr service, GLib.Internal.NonNullableUtf8StringHandle collectionPath, Secret.CollectionFlags flags, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);
}