using System;
using GObject;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY


public abstract class CollectionClassHandle : SafeHandle
{    
    public sealed override bool IsInvalid => handle == IntPtr.Zero;

    protected CollectionClassHandle(bool ownsHandle) : base(IntPtr.Zero, ownsHandle) { }

    public Gio.Internal.DBusProxyClassData GetParentClass()
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    return Marshal.PtrToStructure<CollectionClassData>(handle).ParentClass;
}



    public bool Equals(CollectionClassHandle? other)
    {
        if (ReferenceEquals(null, other))
            return false;

        if (ReferenceEquals(this, other))
            return true;

        return handle.Equals(other.handle);
    }

    public override bool Equals(object? obj)
    {
        return ReferenceEquals(this, obj) || obj is CollectionClassHandle other && Equals(other);
    }

    public override int GetHashCode()
    {
        return handle.GetHashCode();
    }
}

public class CollectionClassUnownedHandle : CollectionClassHandle
{
    private static CollectionClassUnownedHandle? nullHandle;
    public static CollectionClassUnownedHandle NullHandle => nullHandle ??= new CollectionClassUnownedHandle();

    /// <summary>
    /// Creates a new instance of CollectionClassUnownedHandle. Used automatically by PInvoke.
    /// </summary>
    internal CollectionClassUnownedHandle() : base(false) { }

    /// <summary>
    /// Creates a new instance of CollectionClassOwnedHandle. Assumes that the given pointer is unowned by the runtime.
    /// </summary>
    public CollectionClassUnownedHandle(IntPtr ptr) : base(false)
    {
        SetHandle(ptr);
    }

    public CollectionClassOwnedHandle Copy()
    {
        var size = Marshal.SizeOf<CollectionClassData>();
        var ptr = GLib.Functions.Memdup2(handle,(nuint) size);
            
        return new CollectionClassOwnedHandle(ptr);
    }

    protected override bool ReleaseHandle()
    {
        throw new System.Exception("UnownedHandle must not be freed");
    }
}

public class CollectionClassOwnedHandle : CollectionClassHandle
{
    /// <summary>
    /// Creates a new instance of CollectionClassOwnedHandle. Used automatically by PInvoke.
    /// </summary>
    internal CollectionClassOwnedHandle() : base(true) { }

    /// <summary>
    /// Creates a new instance of CollectionClassOwnedHandle. Assumes that the given pointer is owned by the runtime.
    /// </summary>
    public CollectionClassOwnedHandle(IntPtr ptr) : base(true)
    {
        SetHandle(ptr);
    }

    /// <summary>
    /// Creates a new owned Handle
    /// </summary>
    public static CollectionClassOwnedHandle Create()
    {
        var size = Marshal.SizeOf<CollectionClassData>();
        var ptr = GLib.Functions.Malloc((nuint)size);
       
        var str = new CollectionClassData();
        Marshal.StructureToPtr(str, ptr, false);
            
        return new CollectionClassOwnedHandle(ptr);
    }

    public unsafe void CopyTo(IntPtr ptr)
    {
        var data = Marshal.PtrToStructure<CollectionClassData>(handle);
        Marshal.StructureToPtr(data, ptr, false);
    }

    public CollectionClassUnownedHandle UnownedCopy()
    {
        var size = Marshal.SizeOf<CollectionClassData>();
        var ptr = GLib.Functions.Memdup2(handle,(nuint) size);
            
        return new CollectionClassUnownedHandle(ptr);
    }

    protected override bool ReleaseHandle()
    {
        GLib.Functions.Free(handle);
        return true;
    }
}

public abstract class CollectionClassArrayHandle : SafeHandle
{
    public sealed override bool IsInvalid => handle == IntPtr.Zero;

    protected CollectionClassArrayHandle(bool ownsHandle) : base(IntPtr.Zero, ownsHandle) { }
}

public class CollectionClassArrayUnownedHandle : CollectionClassArrayHandle
{
    private static CollectionClassArrayUnownedHandle? nullHandle;
    public static CollectionClassArrayUnownedHandle NullHandle => nullHandle ??= new CollectionClassArrayUnownedHandle();
    
    private int length;

    /// <summary>
    /// Creates a new instance of CollectionClassArrayUnownedHandle. Used automatically by PInvoke.
    /// </summary>
    internal CollectionClassArrayUnownedHandle() : base(false) { }
    
    public CollectionClassArrayUnownedHandle(IntPtr ptr, int length) : base(false)
    {
        this.length = length;
        SetHandle(ptr);
    }

    public Secret.CollectionClass[] ToArray(int length)
    {
        return ToNullableArray(length) ?? throw new InvalidOperationException("Handle is invalid");
    }

    public Secret.CollectionClass[]? ToNullableArray(int length)
    {
        if (IsInvalid)
            return null;
        
        var data = new Secret.CollectionClass[length];
        var currentHandle = handle;
        for(int i = 0; i < length; i++)
        {
            var ownedHandle = new Secret.Internal.CollectionClassUnownedHandle(currentHandle).Copy();
            data[i] = new Secret.CollectionClass(ownedHandle);
            currentHandle += Marshal.SizeOf<Secret.Internal.CollectionClassData>();
        }

        return data;
    }

    protected override bool ReleaseHandle()
    {
        throw new System.Exception("UnownedHandle must not be freed");
    }
}

public class CollectionClassArrayOwnedHandle : CollectionClassArrayHandle
{
    
    //This has no constructor without parameters as we can't supply a length to an array via pinvoke.
    //The length would need to be set manually and the instance be freed via glib.

    private CollectionClassArrayOwnedHandle(IntPtr ptr) : base(true)
    {
        SetHandle(ptr);
    }

    public static CollectionClassArrayOwnedHandle Create(Secret.CollectionClass[] data)
    {
        var size = Marshal.SizeOf<Secret.Internal.CollectionClassData>();
        var ptr = Marshal.AllocHGlobal(size * data.Length);
        var current = ptr;
        for (int i = 0; i < data.Length; i++)
        {
            var structure = Marshal.PtrToStructure<Secret.Internal.CollectionClassData>(data[i].Handle.DangerousGetHandle());
            Marshal.StructureToPtr(structure, current, false);
            current += size;
        }
        
        return new CollectionClassArrayOwnedHandle(ptr);
    }
    
    protected override bool ReleaseHandle()
    {
        Marshal.FreeHGlobal(handle);
        return true;
    }
}