
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY

public static partial class Functions
{
    

/// <summary>
///Calls native function secret_attributes_buildv.
/// </summary>
/// <param name="schema">Transfer ownership: None Nullable: False</param>
/// <param name="va">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_attributes_buildv")]
public static extern GLib.Internal.HashTableOwnedHandle AttributesBuildv(Secret.Internal.SchemaHandle schema, IntPtr va);

/// <summary>
///Calls native function secret_attributes_validate.
///Version: 0.21.2
/// </summary>
/// <param name="schema">Transfer ownership: None Nullable: False</param>
/// <param name="attributes">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[Version("0.21.2")]
[DllImport(ImportResolver.Library, EntryPoint = "secret_attributes_validate")]
public static extern bool AttributesValidate(Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableHandle attributes, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native function secret_backend_get.
///Version: 0.19.0
/// </summary>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[Version("0.19.0")]
[DllImport(ImportResolver.Library, EntryPoint = "secret_backend_get")]
public static extern void BackendGet(Secret.BackendFlags flags, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native function secret_backend_get_finish.
///Version: 0.19.0
/// </summary>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[Version("0.19.0")]
[DllImport(ImportResolver.Library, EntryPoint = "secret_backend_get_finish")]
public static extern IntPtr BackendGetFinish(IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native function secret_error_get_quark.
/// </summary>

/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_error_get_quark")]
public static extern uint ErrorGetQuark();

/// <summary>
///Calls native function secret_get_schema.
///Version: 0.18.6
/// </summary>
/// <param name="type">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[Version("0.18.6")]
[DllImport(ImportResolver.Library, EntryPoint = "secret_get_schema")]
public static extern Secret.Internal.SchemaUnownedHandle GetSchema(Secret.SchemaType type);


/// <summary>
///Calls native function secret_password_clear_finish.
/// </summary>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_password_clear_finish")]
public static extern bool PasswordClearFinish(IntPtr result, out GLib.Internal.ErrorOwnedHandle error);


/// <summary>
///Calls native function secret_password_clearv.
/// </summary>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: Full Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_password_clearv")]
public static extern void PasswordClear(Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableUnownedHandle attributes, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native function secret_password_clearv_sync.
/// </summary>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_password_clearv_sync")]
public static extern bool PasswordClearSync(Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableHandle attributes, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native function secret_password_free.
/// </summary>
/// <param name="password">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_password_free")]
public static extern void PasswordFree(GLib.Internal.NullableUtf8StringHandle password);


/// <summary>
///Calls native function secret_password_lookup_binary_finish.
///Version: 0.19.0
/// </summary>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[Version("0.19.0")]
[DllImport(ImportResolver.Library, EntryPoint = "secret_password_lookup_binary_finish")]
public static extern Secret.Internal.ValueOwnedHandle PasswordLookupBinaryFinish(IntPtr result, out GLib.Internal.ErrorOwnedHandle error);


/// <summary>
///Calls native function secret_password_lookup_finish.
/// </summary>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_password_lookup_finish")]
public static extern GLib.Internal.NonNullableUtf8StringOwnedHandle PasswordLookupFinish(IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native function secret_password_lookup_nonpageable_finish.
/// </summary>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_password_lookup_nonpageable_finish")]
public static extern GLib.Internal.NonNullableUtf8StringOwnedHandle PasswordLookupNonpageableFinish(IntPtr result, out GLib.Internal.ErrorOwnedHandle error);



/// <summary>
///Calls native function secret_password_lookupv.
/// </summary>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: Full Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_password_lookupv")]
public static extern void PasswordLookup(Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableUnownedHandle attributes, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native function secret_password_lookupv_binary_sync.
///Version: 0.19.0
/// </summary>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[Version("0.19.0")]
[DllImport(ImportResolver.Library, EntryPoint = "secret_password_lookupv_binary_sync")]
public static extern Secret.Internal.ValueOwnedHandle PasswordLookupvBinarySync(Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableHandle attributes, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native function secret_password_lookupv_nonpageable_sync.
/// </summary>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_password_lookupv_nonpageable_sync")]
public static extern GLib.Internal.NonNullableUtf8StringOwnedHandle PasswordLookupvNonpageableSync(Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableHandle attributes, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native function secret_password_lookupv_sync.
/// </summary>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_password_lookupv_sync")]
public static extern GLib.Internal.NonNullableUtf8StringOwnedHandle PasswordLookupSync(Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableHandle attributes, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);


/// <summary>
///Calls native function secret_password_search_finish.
///Version: 0.19.0
/// </summary>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[Version("0.19.0")]
[DllImport(ImportResolver.Library, EntryPoint = "secret_password_search_finish")]
public static extern GLib.Internal.ListOwnedHandle PasswordSearchFinish(IntPtr result, out GLib.Internal.ErrorOwnedHandle error);


/// <summary>
///Calls native function secret_password_searchv.
///Version: 0.19.0
/// </summary>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: Full Nullable: False</param>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[Version("0.19.0")]
[DllImport(ImportResolver.Library, EntryPoint = "secret_password_searchv")]
public static extern void PasswordSearch(Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableUnownedHandle attributes, Secret.SearchFlags flags, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native function secret_password_searchv_sync.
///Version: 0.19.0
/// </summary>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: None Nullable: False</param>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[Version("0.19.0")]
[DllImport(ImportResolver.Library, EntryPoint = "secret_password_searchv_sync")]
public static extern GLib.Internal.ListOwnedHandle PasswordSearchSync(Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableHandle attributes, Secret.SearchFlags flags, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);




/// <summary>
///Calls native function secret_password_store_finish.
/// </summary>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_password_store_finish")]
public static extern bool PasswordStoreFinish(IntPtr result, out GLib.Internal.ErrorOwnedHandle error);


/// <summary>
///Calls native function secret_password_storev.
/// </summary>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: Full Nullable: False</param>
/// <param name="collection">Transfer ownership: None Nullable: True</param>
/// <param name="label">Transfer ownership: None Nullable: False</param>
/// <param name="password">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_password_storev")]
public static extern void PasswordStore(Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableUnownedHandle attributes, GLib.Internal.NullableUtf8StringHandle collection, GLib.Internal.NonNullableUtf8StringHandle label, GLib.Internal.NonNullableUtf8StringHandle password, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native function secret_password_storev_binary.
///Version: 0.19.0
/// </summary>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: Full Nullable: False</param>
/// <param name="collection">Transfer ownership: None Nullable: True</param>
/// <param name="label">Transfer ownership: None Nullable: False</param>
/// <param name="value">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[Version("0.19.0")]
[DllImport(ImportResolver.Library, EntryPoint = "secret_password_storev_binary")]
public static extern void PasswordStoreBinary(Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableUnownedHandle attributes, GLib.Internal.NullableUtf8StringHandle collection, GLib.Internal.NonNullableUtf8StringHandle label, Secret.Internal.ValueHandle value, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native function secret_password_storev_binary_sync.
///Version: 0.19.0
/// </summary>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: None Nullable: False</param>
/// <param name="collection">Transfer ownership: None Nullable: True</param>
/// <param name="label">Transfer ownership: None Nullable: False</param>
/// <param name="value">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[Version("0.19.0")]
[DllImport(ImportResolver.Library, EntryPoint = "secret_password_storev_binary_sync")]
public static extern bool PasswordStoreBinarySync(Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableHandle attributes, GLib.Internal.NullableUtf8StringHandle collection, GLib.Internal.NonNullableUtf8StringHandle label, Secret.Internal.ValueHandle value, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native function secret_password_storev_sync.
/// </summary>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: None Nullable: False</param>
/// <param name="collection">Transfer ownership: None Nullable: True</param>
/// <param name="label">Transfer ownership: None Nullable: False</param>
/// <param name="password">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_password_storev_sync")]
public static extern bool PasswordStoreSync(Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableHandle attributes, GLib.Internal.NullableUtf8StringHandle collection, GLib.Internal.NonNullableUtf8StringHandle label, GLib.Internal.NonNullableUtf8StringHandle password, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native function secret_password_wipe.
/// </summary>
/// <param name="password">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_password_wipe")]
public static extern void PasswordWipe(GLib.Internal.NullableUtf8StringHandle password);
}