
using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY


public partial class Item
{
    
/// <summary>
///Calls native function secret_item_get_type.
/// </summary>

/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_item_get_type")]
public static extern nuint GetGType();
    
/// <summary>
///Calls native function secret_item_create.
/// </summary>
/// <param name="collection">Transfer ownership: None Nullable: False</param>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: None Nullable: False</param>
/// <param name="label">Transfer ownership: None Nullable: False</param>
/// <param name="value">Transfer ownership: None Nullable: False</param>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_item_create")]
public static extern void Create(IntPtr collection, Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableHandle attributes, GLib.Internal.NonNullableUtf8StringHandle label, Secret.Internal.ValueHandle value, Secret.ItemCreateFlags flags, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native function secret_item_create_finish.
/// </summary>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_item_create_finish")]
public static extern IntPtr CreateFinish(IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native function secret_item_create_sync.
/// </summary>
/// <param name="collection">Transfer ownership: None Nullable: False</param>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: None Nullable: False</param>
/// <param name="label">Transfer ownership: None Nullable: False</param>
/// <param name="value">Transfer ownership: None Nullable: False</param>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_item_create_sync")]
public static extern IntPtr CreateSync(IntPtr collection, Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableHandle attributes, GLib.Internal.NonNullableUtf8StringHandle label, Secret.Internal.ValueHandle value, Secret.ItemCreateFlags flags, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native function secret_item_load_secrets.
/// </summary>
/// <param name="items">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_item_load_secrets")]
public static extern void LoadSecrets(GLib.Internal.ListHandle items, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native function secret_item_load_secrets_finish.
/// </summary>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_item_load_secrets_finish")]
public static extern bool LoadSecretsFinish(IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native function secret_item_load_secrets_sync.
/// </summary>
/// <param name="items">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_item_load_secrets_sync")]
public static extern bool LoadSecretsSync(GLib.Internal.ListHandle items, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native function secret_item_new_for_dbus_path.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: True</param>
/// <param name="itemPath">Transfer ownership: None Nullable: False</param>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_item_new_for_dbus_path")]
public static extern void NewForDbusPath(IntPtr service, GLib.Internal.NonNullableUtf8StringHandle itemPath, Secret.ItemFlags flags, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);
    
/// <summary>
///Calls native method secret_item_delete.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_delete")]
public static extern void Delete(IntPtr self, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_item_delete_finish.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_delete_finish")]
public static extern bool DeleteFinish(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_item_delete_sync.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_delete_sync")]
public static extern bool DeleteSync(IntPtr self, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_item_get_attributes.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_get_attributes")]
public static extern GLib.Internal.HashTableOwnedHandle GetAttributes(IntPtr self);

/// <summary>
///Calls native method secret_item_get_created.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_get_created")]
public static extern ulong GetCreated(IntPtr self);

/// <summary>
///Calls native method secret_item_get_flags.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_get_flags")]
public static extern Secret.ItemFlags GetFlags(IntPtr self);

/// <summary>
///Calls native method secret_item_get_label.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_get_label")]
public static extern GLib.Internal.NonNullableUtf8StringOwnedHandle GetLabel(IntPtr self);

/// <summary>
///Calls native method secret_item_get_locked.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_get_locked")]
public static extern bool GetLocked(IntPtr self);

/// <summary>
///Calls native method secret_item_get_modified.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_get_modified")]
public static extern ulong GetModified(IntPtr self);

/// <summary>
///Calls native method secret_item_get_schema_name.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: Full Nullable: True</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_get_schema_name")]
public static extern GLib.Internal.NullableUtf8StringOwnedHandle GetSchemaName(IntPtr self);

/// <summary>
///Calls native method secret_item_get_secret.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: Full Nullable: True</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_get_secret")]
public static extern Secret.Internal.ValueOwnedHandle GetSecret(IntPtr self);

/// <summary>
///Calls native method secret_item_get_service.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_get_service")]
public static extern IntPtr GetService(IntPtr self);

/// <summary>
///Calls native method secret_item_load_secret.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_load_secret")]
public static extern void LoadSecret(IntPtr self, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_item_load_secret_finish.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_load_secret_finish")]
public static extern bool LoadSecretFinish(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_item_load_secret_sync.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_load_secret_sync")]
public static extern bool LoadSecretSync(IntPtr self, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_item_refresh.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_refresh")]
public static extern void Refresh(IntPtr self);

/// <summary>
///Calls native method secret_item_set_attributes.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_set_attributes")]
public static extern void SetAttributes(IntPtr self, Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableHandle attributes, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_item_set_attributes_finish.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_set_attributes_finish")]
public static extern bool SetAttributesFinish(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_item_set_attributes_sync.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_set_attributes_sync")]
public static extern bool SetAttributesSync(IntPtr self, Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableHandle attributes, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_item_set_label.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="label">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_set_label")]
public static extern void SetLabel(IntPtr self, GLib.Internal.NonNullableUtf8StringHandle label, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_item_set_label_finish.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_set_label_finish")]
public static extern bool SetLabelFinish(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_item_set_label_sync.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="label">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_set_label_sync")]
public static extern bool SetLabelSync(IntPtr self, GLib.Internal.NonNullableUtf8StringHandle label, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_item_set_secret.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="value">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_set_secret")]
public static extern void SetSecret(IntPtr self, Secret.Internal.ValueHandle value, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_item_set_secret_finish.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_set_secret_finish")]
public static extern bool SetSecretFinish(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_item_set_secret_sync.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="value">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_set_secret_sync")]
public static extern bool SetSecretSync(IntPtr self, Secret.Internal.ValueHandle value, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);
    
/// <summary>
///Calls native constructor secret_item_new_for_dbus_path_finish.
/// </summary>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_new_for_dbus_path_finish")]
public static extern IntPtr NewForDbusPathFinish(IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native constructor secret_item_new_for_dbus_path_sync.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: True</param>
/// <param name="itemPath">Transfer ownership: None Nullable: False</param>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_item_new_for_dbus_path_sync")]
public static extern IntPtr NewForDbusPathSync(IntPtr service, GLib.Internal.NonNullableUtf8StringHandle itemPath, Secret.ItemFlags flags, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);
}