
using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY


public partial class Prompt
{
    
/// <summary>
///Calls native function secret_prompt_get_type.
/// </summary>

/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_prompt_get_type")]
public static extern nuint GetGType();
    
    
/// <summary>
///Calls native method secret_prompt_perform.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="windowId">Transfer ownership: None Nullable: True</param>
/// <param name="returnType">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_prompt_perform")]
public static extern void Perform(IntPtr self, GLib.Internal.NullableUtf8StringHandle windowId, GLib.Internal.VariantTypeHandle returnType, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_prompt_perform_finish.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_prompt_perform_finish")]
public static extern GLib.Internal.VariantOwnedHandle PerformFinish(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_prompt_perform_sync.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="windowId">Transfer ownership: None Nullable: True</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="returnType">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_prompt_perform_sync")]
public static extern GLib.Internal.VariantOwnedHandle PerformSync(IntPtr self, GLib.Internal.NullableUtf8StringHandle windowId, IntPtr cancellable, GLib.Internal.VariantTypeHandle returnType, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_prompt_run.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="windowId">Transfer ownership: None Nullable: True</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="returnType">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_prompt_run")]
public static extern GLib.Internal.VariantOwnedHandle Run(IntPtr self, GLib.Internal.NullableUtf8StringHandle windowId, IntPtr cancellable, GLib.Internal.VariantTypeHandle returnType, out GLib.Internal.ErrorOwnedHandle error);
    
}