
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY


[StructLayout(LayoutKind.Sequential)]
public partial struct PromptClassData
{
    

     public Gio.Internal.DBusProxyClassData ParentClass;
[MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)] public IntPtr[] Padding;
}