using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY


public abstract class PromptPrivateHandle : SafeHandle
{
    public sealed override bool IsInvalid => handle == IntPtr.Zero;

    protected PromptPrivateHandle(bool ownsHandle) : base(IntPtr.Zero, ownsHandle) { }

    public PromptPrivateOwnedHandle OwnedCopy() => throw new NotSupportedException("Can't create a copy of this handle");
    public PromptPrivateUnownedHandle UnownedCopy() => throw new NotSupportedException("Can't create a copy of this handle");

    public bool Equals(PromptPrivateHandle? other)
    {
        if (ReferenceEquals(null, other))
            return false;

        if (ReferenceEquals(this, other))
            return true;

        return handle.Equals(other.handle);
    }

    public override bool Equals(object? obj)
    {
        return ReferenceEquals(this, obj) || obj is PromptPrivateHandle other && Equals(other);
    }

    public override int GetHashCode()
    {
        return handle.GetHashCode();
    }
}

public class PromptPrivateUnownedHandle : PromptPrivateHandle
{
    private static PromptPrivateUnownedHandle? nullHandle;
    public static PromptPrivateUnownedHandle NullHandle => nullHandle ??= new PromptPrivateUnownedHandle();

    /// <summary>
    /// Creates a new instance of PromptPrivateUnownedHandle. Used automatically by PInvoke.
    /// </summary>
    internal PromptPrivateUnownedHandle() : base(false) { }

    /// <summary>
    /// Creates a new instance of PromptPrivateUnownedHandle. Assumes that the given pointer is unowned by the runtime.
    /// </summary>
    public PromptPrivateUnownedHandle(IntPtr ptr) : base(false)
    {
        SetHandle(ptr);
    }

    protected override bool ReleaseHandle()
    {
        throw new System.Exception("UnownedHandle must not be freed");
    }
}

public class PromptPrivateOwnedHandle : PromptPrivateHandle
{
    /// <summary>
    /// Creates a new instance of PromptPrivateOwnedHandle. Used automatically by PInvoke.
    /// </summary>
    internal PromptPrivateOwnedHandle() : base(true) { }

    /// <summary>
    /// Creates a new instance of PromptPrivateOwnedHandle. Assumes that the given pointer is owned by the runtime.
    /// </summary>
    public PromptPrivateOwnedHandle(IntPtr ptr) : base(true)
    {
        SetHandle(ptr);
    }

    /// <summary>
    /// Create a PromptPrivateOwnedHandle from a pointer that is assumed unowned.
    /// </summary>
    /// <param name="ptr">A pointer to a PromptPrivate which is not owned by the runtime.</param>
    /// <returns>A PromptPrivateOwnedHandle</returns>
    public static PromptPrivateOwnedHandle FromUnowned(IntPtr ptr) => throw new NotSupportedException("Can't create a copy of this handle");

    protected override bool ReleaseHandle() => throw new NotSupportedException("Can't free this handle");
}