
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY


[StructLayout(LayoutKind.Sequential)]
public partial struct PromptData
{
     public Gio.Internal.DBusProxyData ParentInstance;
 public IntPtr Pv;
}