
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY


[StructLayout(LayoutKind.Sequential)]
public partial struct RetrievableInterfaceData
{
    public delegate void RetrieveSecretCallback(IntPtr self, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);
public delegate IntPtr RetrieveSecretFinishCallback(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

     public GObject.Internal.TypeInterfaceData ParentIface;
 public RetrieveSecretCallback RetrieveSecret;
 public RetrieveSecretFinishCallback RetrieveSecretFinish;
}