
using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY


public partial class Retrievable
{
    
/// <summary>
///Calls native function secret_retrievable_get_type.
/// </summary>

/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_retrievable_get_type")]
public static extern nuint GetGType();
    
    
/// <summary>
///Calls native method secret_retrievable_get_attributes.
///Version: 0.19.0
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: Full Nullable: False</returns>
[Version("0.19.0")]
[DllImport(ImportResolver.Library, EntryPoint = "secret_retrievable_get_attributes")]
public static extern GLib.Internal.HashTableOwnedHandle GetAttributes(IntPtr self);

/// <summary>
///Calls native method secret_retrievable_get_created.
///Version: 0.19.0
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: False</returns>
[Version("0.19.0")]
[DllImport(ImportResolver.Library, EntryPoint = "secret_retrievable_get_created")]
public static extern ulong GetCreated(IntPtr self);

/// <summary>
///Calls native method secret_retrievable_get_label.
///Version: 0.19.0
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: Full Nullable: False</returns>
[Version("0.19.0")]
[DllImport(ImportResolver.Library, EntryPoint = "secret_retrievable_get_label")]
public static extern GLib.Internal.NonNullableUtf8StringOwnedHandle GetLabel(IntPtr self);

/// <summary>
///Calls native method secret_retrievable_get_modified.
///Version: 0.19.0
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: False</returns>
[Version("0.19.0")]
[DllImport(ImportResolver.Library, EntryPoint = "secret_retrievable_get_modified")]
public static extern ulong GetModified(IntPtr self);

/// <summary>
///Calls native method secret_retrievable_retrieve_secret.
///Version: 0.19.0
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>
[Version("0.19.0")]
[DllImport(ImportResolver.Library, EntryPoint = "secret_retrievable_retrieve_secret")]
public static extern void RetrieveSecret(IntPtr self, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_retrievable_retrieve_secret_finish.
///Version: 0.19.0
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: True</returns>
[Version("0.19.0")]
[DllImport(ImportResolver.Library, EntryPoint = "secret_retrievable_retrieve_secret_finish")]
public static extern Secret.Internal.ValueOwnedHandle RetrieveSecretFinish(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_retrievable_retrieve_secret_sync.
///Version: 0.19.0
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: Full Nullable: True</returns>
[Version("0.19.0")]
[DllImport(ImportResolver.Library, EntryPoint = "secret_retrievable_retrieve_secret_sync")]
public static extern Secret.Internal.ValueOwnedHandle RetrieveSecretSync(IntPtr self, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);
}