using System;
using GObject;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY


public abstract class RetrievableInterfaceHandle : SafeHandle
{    
    public sealed override bool IsInvalid => handle == IntPtr.Zero;

    protected RetrievableInterfaceHandle(bool ownsHandle) : base(IntPtr.Zero, ownsHandle) { }

    public GObject.Internal.TypeInterfaceData GetParentIface()
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    return Marshal.PtrToStructure<RetrievableInterfaceData>(handle).ParentIface;
}

public RetrievableInterfaceData.RetrieveSecretCallback GetRetrieveSecret()
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    return Marshal.PtrToStructure<RetrievableInterfaceData>(handle).RetrieveSecret;
}

public RetrievableInterfaceData.RetrieveSecretFinishCallback GetRetrieveSecretFinish()
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    return Marshal.PtrToStructure<RetrievableInterfaceData>(handle).RetrieveSecretFinish;
}


    public bool Equals(RetrievableInterfaceHandle? other)
    {
        if (ReferenceEquals(null, other))
            return false;

        if (ReferenceEquals(this, other))
            return true;

        return handle.Equals(other.handle);
    }

    public override bool Equals(object? obj)
    {
        return ReferenceEquals(this, obj) || obj is RetrievableInterfaceHandle other && Equals(other);
    }

    public override int GetHashCode()
    {
        return handle.GetHashCode();
    }
}

public class RetrievableInterfaceUnownedHandle : RetrievableInterfaceHandle
{
    private static RetrievableInterfaceUnownedHandle? nullHandle;
    public static RetrievableInterfaceUnownedHandle NullHandle => nullHandle ??= new RetrievableInterfaceUnownedHandle();

    /// <summary>
    /// Creates a new instance of RetrievableInterfaceUnownedHandle. Used automatically by PInvoke.
    /// </summary>
    internal RetrievableInterfaceUnownedHandle() : base(false) { }

    /// <summary>
    /// Creates a new instance of RetrievableInterfaceOwnedHandle. Assumes that the given pointer is unowned by the runtime.
    /// </summary>
    public RetrievableInterfaceUnownedHandle(IntPtr ptr) : base(false)
    {
        SetHandle(ptr);
    }

    public RetrievableInterfaceOwnedHandle Copy()
    {
        var size = Marshal.SizeOf<RetrievableInterfaceData>();
        var ptr = GLib.Functions.Memdup2(handle,(nuint) size);
            
        return new RetrievableInterfaceOwnedHandle(ptr);
    }

    protected override bool ReleaseHandle()
    {
        throw new System.Exception("UnownedHandle must not be freed");
    }
}

public class RetrievableInterfaceOwnedHandle : RetrievableInterfaceHandle
{
    /// <summary>
    /// Creates a new instance of RetrievableInterfaceOwnedHandle. Used automatically by PInvoke.
    /// </summary>
    internal RetrievableInterfaceOwnedHandle() : base(true) { }

    /// <summary>
    /// Creates a new instance of RetrievableInterfaceOwnedHandle. Assumes that the given pointer is owned by the runtime.
    /// </summary>
    public RetrievableInterfaceOwnedHandle(IntPtr ptr) : base(true)
    {
        SetHandle(ptr);
    }

    /// <summary>
    /// Creates a new owned Handle
    /// </summary>
    public static RetrievableInterfaceOwnedHandle Create()
    {
        var size = Marshal.SizeOf<RetrievableInterfaceData>();
        var ptr = GLib.Functions.Malloc((nuint)size);
       
        var str = new RetrievableInterfaceData();
        Marshal.StructureToPtr(str, ptr, false);
            
        return new RetrievableInterfaceOwnedHandle(ptr);
    }

    public unsafe void CopyTo(IntPtr ptr)
    {
        var data = Marshal.PtrToStructure<RetrievableInterfaceData>(handle);
        Marshal.StructureToPtr(data, ptr, false);
    }

    public RetrievableInterfaceUnownedHandle UnownedCopy()
    {
        var size = Marshal.SizeOf<RetrievableInterfaceData>();
        var ptr = GLib.Functions.Memdup2(handle,(nuint) size);
            
        return new RetrievableInterfaceUnownedHandle(ptr);
    }

    protected override bool ReleaseHandle()
    {
        GLib.Functions.Free(handle);
        return true;
    }
}

public abstract class RetrievableInterfaceArrayHandle : SafeHandle
{
    public sealed override bool IsInvalid => handle == IntPtr.Zero;

    protected RetrievableInterfaceArrayHandle(bool ownsHandle) : base(IntPtr.Zero, ownsHandle) { }
}

public class RetrievableInterfaceArrayUnownedHandle : RetrievableInterfaceArrayHandle
{
    private static RetrievableInterfaceArrayUnownedHandle? nullHandle;
    public static RetrievableInterfaceArrayUnownedHandle NullHandle => nullHandle ??= new RetrievableInterfaceArrayUnownedHandle();
    
    private int length;

    /// <summary>
    /// Creates a new instance of RetrievableInterfaceArrayUnownedHandle. Used automatically by PInvoke.
    /// </summary>
    internal RetrievableInterfaceArrayUnownedHandle() : base(false) { }
    
    public RetrievableInterfaceArrayUnownedHandle(IntPtr ptr, int length) : base(false)
    {
        this.length = length;
        SetHandle(ptr);
    }

    public Secret.RetrievableInterface[] ToArray(int length)
    {
        return ToNullableArray(length) ?? throw new InvalidOperationException("Handle is invalid");
    }

    public Secret.RetrievableInterface[]? ToNullableArray(int length)
    {
        if (IsInvalid)
            return null;
        
        var data = new Secret.RetrievableInterface[length];
        var currentHandle = handle;
        for(int i = 0; i < length; i++)
        {
            var ownedHandle = new Secret.Internal.RetrievableInterfaceUnownedHandle(currentHandle).Copy();
            data[i] = new Secret.RetrievableInterface(ownedHandle);
            currentHandle += Marshal.SizeOf<Secret.Internal.RetrievableInterfaceData>();
        }

        return data;
    }

    protected override bool ReleaseHandle()
    {
        throw new System.Exception("UnownedHandle must not be freed");
    }
}

public class RetrievableInterfaceArrayOwnedHandle : RetrievableInterfaceArrayHandle
{
    
    //This has no constructor without parameters as we can't supply a length to an array via pinvoke.
    //The length would need to be set manually and the instance be freed via glib.

    private RetrievableInterfaceArrayOwnedHandle(IntPtr ptr) : base(true)
    {
        SetHandle(ptr);
    }

    public static RetrievableInterfaceArrayOwnedHandle Create(Secret.RetrievableInterface[] data)
    {
        var size = Marshal.SizeOf<Secret.Internal.RetrievableInterfaceData>();
        var ptr = Marshal.AllocHGlobal(size * data.Length);
        var current = ptr;
        for (int i = 0; i < data.Length; i++)
        {
            var structure = Marshal.PtrToStructure<Secret.Internal.RetrievableInterfaceData>(data[i].Handle.DangerousGetHandle());
            Marshal.StructureToPtr(structure, current, false);
            current += size;
        }
        
        return new RetrievableInterfaceArrayOwnedHandle(ptr);
    }
    
    protected override bool ReleaseHandle()
    {
        Marshal.FreeHGlobal(handle);
        return true;
    }
}