using System;
using GObject;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY


public abstract class SchemaAttributeHandle : SafeHandle, IEquatable<SchemaAttributeHandle>
{    
    public sealed override bool IsInvalid => handle == IntPtr.Zero;

    protected SchemaAttributeHandle(bool ownsHandle) : base(IntPtr.Zero, ownsHandle) { }

    

    public SchemaAttributeOwnedHandle OwnedCopy()
    {
        var ptr = GObject.Internal.Functions.BoxedCopy(Secret.Internal.SchemaAttribute.GetGType(), handle);
        return new SchemaAttributeOwnedHandle(ptr);
    }
    
    public SchemaAttributeUnownedHandle UnownedCopy()
    {
        var ptr = GObject.Internal.Functions.BoxedCopy(Secret.Internal.SchemaAttribute.GetGType(), handle);
        return new SchemaAttributeUnownedHandle(ptr);
    }

    public unsafe IntPtr GetName()
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    return Marshal.PtrToStructure<SchemaAttributeData>(handle).Name;
}
public unsafe void SetName(IntPtr value)
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    var data = Marshal.PtrToStructure<SchemaAttributeData>(handle);
    data.Name = value;
    Marshal.StructureToPtr(data, handle, false);
}

public unsafe Secret.SchemaAttributeType GetType()
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    return Marshal.PtrToStructure<SchemaAttributeData>(handle).Type;
}
public unsafe void SetType(Secret.SchemaAttributeType value)
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    var data = Marshal.PtrToStructure<SchemaAttributeData>(handle);
    data.Type = value;
    Marshal.StructureToPtr(data, handle, false);
}


    public bool Equals(SchemaAttributeHandle? other)
    {
        if (ReferenceEquals(null, other))
            return false;

        if (ReferenceEquals(this, other))
            return true;

        return handle.Equals(other.handle);
    }

    public override bool Equals(object? obj)
    {
        return ReferenceEquals(this, obj) || obj is SchemaAttributeHandle other && Equals(other);
    }

    public override int GetHashCode()
    {
        return handle.GetHashCode();
    }
}

public class SchemaAttributeUnownedHandle : SchemaAttributeHandle
{
    private static SchemaAttributeUnownedHandle? nullHandle;
    public static SchemaAttributeUnownedHandle NullHandle => nullHandle ??= new SchemaAttributeUnownedHandle();

    /// <summary>
    /// Creates a new instance of SchemaAttributeUnownedHandle. Used automatically by PInvoke.
    /// </summary>
    internal SchemaAttributeUnownedHandle() : base(false) { }

    /// <summary>
    /// Creates a new instance of SchemaAttributeOwnedHandle. Assumes that the given pointer is unowned by the runtime.
    /// </summary>
    public SchemaAttributeUnownedHandle(IntPtr ptr) : base(false)
    {
        SetHandle(ptr);
    }

    protected override bool ReleaseHandle()
    {
        throw new System.Exception("UnownedHandle must not be freed");
    }
}

public class SchemaAttributeOwnedHandle : SchemaAttributeHandle
{
    /// <summary>
    /// Creates a new instance of SchemaAttributeOwnedHandle. Used automatically by PInvoke.
    /// </summary>
    internal SchemaAttributeOwnedHandle() : base(true) { }

    /// <summary>
    /// Creates a new instance of SchemaAttributeOwnedHandle. Assumes that the given pointer is owned by the runtime.
    /// </summary>
    public SchemaAttributeOwnedHandle(IntPtr ptr) : base(true)
    {
        SetHandle(ptr);
    }

    

    /// <summary>
    /// Create a SchemaAttributeOwnedHandle from a pointer that is assumed unowned. To do so a
    /// boxed copy is created of the given pointer to be used as the handle.
    /// </summary>
    /// <param name="ptr">A pointer to a SchemaAttribute which is not owned by the runtime.</param>
    /// <returns>A SchemaAttributeOwnedHandle</returns>
    public static SchemaAttributeOwnedHandle FromUnowned(IntPtr ptr)
    {
        var ownedPtr = GObject.Internal.Functions.BoxedCopy(Secret.Internal.SchemaAttribute.GetGType(), ptr);
        return new SchemaAttributeOwnedHandle(ownedPtr);
    }

    protected override bool ReleaseHandle()
    {
        GObject.Internal.Functions.BoxedFree(Secret.Internal.SchemaAttribute.GetGType(), handle);
        return true;
    }
}

public class SchemaAttributeManagedHandle : SchemaAttributeOwnedHandle
{
    private SchemaAttributeManagedHandle(IntPtr handle) : base(handle) 
    {
    }

    public static SchemaAttributeManagedHandle Create()
    {
        var size = Marshal.SizeOf<SchemaAttributeData>();
        var ptr = GLib.Functions.Malloc((nuint)size);
       
        var str = new SchemaAttributeData();
        Marshal.StructureToPtr(str, ptr, false);
            
        return new SchemaAttributeManagedHandle(ptr);
    }

    protected override bool ReleaseHandle()
    {
        GObject.Internal.Functions.BoxedFree(Secret.Internal.SchemaAttribute.GetGType(), handle);
        return true;
    }
}

public abstract class SchemaAttributeArrayHandle : SafeHandle
{
    public sealed override bool IsInvalid => handle == IntPtr.Zero;

    protected SchemaAttributeArrayHandle(bool ownsHandle) : base(IntPtr.Zero, ownsHandle) { }
}

public class SchemaAttributeArrayUnownedHandle : SchemaAttributeArrayHandle
{
    private static SchemaAttributeArrayUnownedHandle? nullHandle;
    public static SchemaAttributeArrayUnownedHandle NullHandle => nullHandle ??= new SchemaAttributeArrayUnownedHandle();
    
    private int length;

    /// <summary>
    /// Creates a new instance of SchemaAttributeArrayUnownedHandle. Used automatically by PInvoke.
    /// </summary>
    internal SchemaAttributeArrayUnownedHandle() : base(false) { }
    
    public SchemaAttributeArrayUnownedHandle(IntPtr ptr, int length) : base(false)
    {
        this.length = length;
        SetHandle(ptr);
    }

    public Secret.SchemaAttribute[] ToArray(int length)
    {
        return ToNullableArray(length) ?? throw new InvalidOperationException("Handle is invalid");
    }

    public Secret.SchemaAttribute[]? ToNullableArray(int length)
    {
        if (IsInvalid)
            return null;
        
        var data = new Secret.SchemaAttribute[length];
        var currentHandle = handle;
        for(int i = 0; i < length; i++)
        {
            var ownedHandle = new Secret.Internal.SchemaAttributeUnownedHandle(currentHandle).OwnedCopy();
            data[i] = new Secret.SchemaAttribute(ownedHandle);
            currentHandle += Marshal.SizeOf<Secret.Internal.SchemaAttributeData>();
        }

        return data;
    }

    protected override bool ReleaseHandle()
    {
        throw new System.Exception("UnownedHandle must not be freed");
    }
}

public class SchemaAttributeArrayOwnedHandle : SchemaAttributeArrayHandle
{
    
    //This has no constructor without parameters as we can't supply a length to an array via pinvoke.
    //The length would need to be set manually and the instance be freed via glib.

    private SchemaAttributeArrayOwnedHandle(IntPtr ptr) : base(true)
    {
        SetHandle(ptr);
    }

    public static SchemaAttributeArrayOwnedHandle Create(Secret.SchemaAttribute[] data)
    {
        var size = Marshal.SizeOf<Secret.Internal.SchemaAttributeData>();
        var ptr = Marshal.AllocHGlobal(size * data.Length);
        var current = ptr;
        for (int i = 0; i < data.Length; i++)
        {
            Marshal.StructureToPtr(data[i], current, false);
            current += size;
        }
        
        return new SchemaAttributeArrayOwnedHandle(ptr);
    }
    
    protected override bool ReleaseHandle()
    {
        Marshal.FreeHGlobal(handle);
        return true;
    }
}