
using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY


public partial class SchemaAttribute
{
    
    
/// <summary>
///Calls native function secret_schema_attribute_get_type.
/// </summary>

/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_schema_attribute_get_type")]
public static extern nuint GetGType();
    
    
}