
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY


[StructLayout(LayoutKind.Sequential)]
public partial struct ServiceClassData
{
    public delegate IntPtr PromptSyncCallback(IntPtr self, IntPtr prompt, IntPtr cancellable, IntPtr returnType, out GLib.Internal.ErrorOwnedHandle error);
public delegate void PromptAsyncCallback(IntPtr self, IntPtr prompt, IntPtr returnType, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);
public delegate IntPtr PromptFinishCallback(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);
public delegate nuint GetCollectionGtypeCallback(IntPtr self);
public delegate nuint GetItemGtypeCallback(IntPtr self);

     public Gio.Internal.DBusProxyClassData ParentClass;
 public nuint CollectionGtype;
 public nuint ItemGtype;
 public PromptSyncCallback PromptSync;
 public PromptAsyncCallback PromptAsync;
 public PromptFinishCallback PromptFinish;
 public GetCollectionGtypeCallback GetCollectionGtype;
 public GetItemGtypeCallback GetItemGtype;
[MarshalAs(UnmanagedType.ByValArray, SizeConst = 14)] public IntPtr[] Padding;
}