
using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY


public partial class Service
{
    
/// <summary>
///Calls native function secret_service_get_type.
/// </summary>

/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_service_get_type")]
public static extern nuint GetGType();
    
/// <summary>
///Calls native function secret_service_disconnect.
/// </summary>

/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_service_disconnect")]
public static extern void Disconnect();

/// <summary>
///Calls native function secret_service_get.
/// </summary>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_service_get")]
public static extern void Get(Secret.ServiceFlags flags, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native function secret_service_get_finish.
/// </summary>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_service_get_finish")]
public static extern IntPtr GetFinish(IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native function secret_service_get_sync.
/// </summary>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_service_get_sync")]
public static extern IntPtr GetSync(Secret.ServiceFlags flags, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native function secret_service_open.
/// </summary>
/// <param name="serviceGtype">Transfer ownership: None Nullable: False</param>
/// <param name="serviceBusName">Transfer ownership: None Nullable: True</param>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_service_open")]
public static extern void Open(GObject.Type serviceGtype, GLib.Internal.NullableUtf8StringHandle serviceBusName, Secret.ServiceFlags flags, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native function secret_service_open_finish.
/// </summary>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_service_open_finish")]
public static extern IntPtr OpenFinish(IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native function secret_service_open_sync.
/// </summary>
/// <param name="serviceGtype">Transfer ownership: None Nullable: False</param>
/// <param name="serviceBusName">Transfer ownership: None Nullable: True</param>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_service_open_sync")]
public static extern IntPtr OpenSync(GObject.Type serviceGtype, GLib.Internal.NullableUtf8StringHandle serviceBusName, Secret.ServiceFlags flags, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);
    
/// <summary>
///Calls native method secret_service_clear.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: True</param>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_clear")]
public static extern void Clear(IntPtr service, Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableHandle attributes, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_service_clear_finish.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: True</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_clear_finish")]
public static extern bool ClearFinish(IntPtr service, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_clear_sync.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: True</param>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_clear_sync")]
public static extern bool ClearSync(IntPtr service, Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableHandle attributes, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_create_collection_dbus_path.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="properties">Transfer ownership: None Nullable: False</param>
/// <param name="alias">Transfer ownership: None Nullable: True</param>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_create_collection_dbus_path")]
public static extern void CreateCollectionDbusPath(IntPtr self, GLib.Internal.HashTableHandle properties, GLib.Internal.NullableUtf8StringHandle alias, Secret.CollectionCreateFlags flags, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_service_create_collection_dbus_path_finish.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_create_collection_dbus_path_finish")]
public static extern GLib.Internal.NonNullableUtf8StringOwnedHandle CreateCollectionDbusPathFinish(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_create_collection_dbus_path_sync.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="properties">Transfer ownership: None Nullable: False</param>
/// <param name="alias">Transfer ownership: None Nullable: True</param>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_create_collection_dbus_path_sync")]
public static extern GLib.Internal.NonNullableUtf8StringOwnedHandle CreateCollectionDbusPathSync(IntPtr self, GLib.Internal.HashTableHandle properties, GLib.Internal.NullableUtf8StringHandle alias, Secret.CollectionCreateFlags flags, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_create_item_dbus_path.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="collectionPath">Transfer ownership: None Nullable: False</param>
/// <param name="properties">Transfer ownership: None Nullable: False</param>
/// <param name="value">Transfer ownership: None Nullable: False</param>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_create_item_dbus_path")]
public static extern void CreateItemDbusPath(IntPtr self, GLib.Internal.NonNullableUtf8StringHandle collectionPath, GLib.Internal.HashTableHandle properties, Secret.Internal.ValueHandle value, Secret.ItemCreateFlags flags, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_service_create_item_dbus_path_finish.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_create_item_dbus_path_finish")]
public static extern GLib.Internal.NonNullableUtf8StringOwnedHandle CreateItemDbusPathFinish(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_create_item_dbus_path_sync.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="collectionPath">Transfer ownership: None Nullable: False</param>
/// <param name="properties">Transfer ownership: None Nullable: False</param>
/// <param name="value">Transfer ownership: None Nullable: False</param>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_create_item_dbus_path_sync")]
public static extern GLib.Internal.NonNullableUtf8StringOwnedHandle CreateItemDbusPathSync(IntPtr self, GLib.Internal.NonNullableUtf8StringHandle collectionPath, GLib.Internal.HashTableHandle properties, Secret.Internal.ValueHandle value, Secret.ItemCreateFlags flags, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_decode_dbus_secret.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: False</param>
/// <param name="value">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_decode_dbus_secret")]
public static extern Secret.Internal.ValueOwnedHandle DecodeDbusSecret(IntPtr service, GLib.Internal.VariantHandle value);

/// <summary>
///Calls native method secret_service_delete_item_dbus_path.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="itemPath">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_delete_item_dbus_path")]
public static extern void DeleteItemDbusPath(IntPtr self, GLib.Internal.NonNullableUtf8StringHandle itemPath, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_service_delete_item_dbus_path_finish.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_delete_item_dbus_path_finish")]
public static extern bool DeleteItemDbusPathFinish(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_delete_item_dbus_path_sync.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="itemPath">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_delete_item_dbus_path_sync")]
public static extern bool DeleteItemDbusPathSync(IntPtr self, GLib.Internal.NonNullableUtf8StringHandle itemPath, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_encode_dbus_secret.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: False</param>
/// <param name="value">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_encode_dbus_secret")]
public static extern GLib.Internal.VariantUnownedHandle EncodeDbusSecret(IntPtr service, Secret.Internal.ValueHandle value);

/// <summary>
///Calls native method secret_service_ensure_session.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_ensure_session")]
public static extern void EnsureSession(IntPtr self, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_service_ensure_session_finish.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_ensure_session_finish")]
public static extern bool EnsureSessionFinish(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_ensure_session_sync.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_ensure_session_sync")]
public static extern bool EnsureSessionSync(IntPtr self, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_get_collection_gtype.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_get_collection_gtype")]
public static extern nuint GetCollectionGtype(IntPtr self);

/// <summary>
///Calls native method secret_service_get_collections.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: Full Nullable: True</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_get_collections")]
public static extern GLib.Internal.ListOwnedHandle GetCollections(IntPtr self);

/// <summary>
///Calls native method secret_service_get_flags.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_get_flags")]
public static extern Secret.ServiceFlags GetFlags(IntPtr self);

/// <summary>
///Calls native method secret_service_get_item_gtype.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_get_item_gtype")]
public static extern nuint GetItemGtype(IntPtr self);

/// <summary>
///Calls native method secret_service_get_secret_for_dbus_path.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="itemPath">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_get_secret_for_dbus_path")]
public static extern void GetSecretForDbusPath(IntPtr self, GLib.Internal.NonNullableUtf8StringHandle itemPath, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_service_get_secret_for_dbus_path_finish.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: True</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_get_secret_for_dbus_path_finish")]
public static extern Secret.Internal.ValueOwnedHandle GetSecretForDbusPathFinish(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_get_secret_for_dbus_path_sync.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="itemPath">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: Full Nullable: True</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_get_secret_for_dbus_path_sync")]
public static extern Secret.Internal.ValueOwnedHandle GetSecretForDbusPathSync(IntPtr self, GLib.Internal.NonNullableUtf8StringHandle itemPath, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_get_secrets_for_dbus_paths.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="itemPaths">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_get_secrets_for_dbus_paths")]
public static extern void GetSecretsForDbusPaths(IntPtr self, GLib.Internal.NonNullableUtf8StringHandle itemPaths, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_service_get_secrets_for_dbus_paths_finish.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_get_secrets_for_dbus_paths_finish")]
public static extern GLib.Internal.HashTableOwnedHandle GetSecretsForDbusPathsFinish(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_get_secrets_for_dbus_paths_sync.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="itemPaths">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_get_secrets_for_dbus_paths_sync")]
public static extern GLib.Internal.HashTableOwnedHandle GetSecretsForDbusPathsSync(IntPtr self, GLib.Internal.NonNullableUtf8StringHandle itemPaths, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_get_session_algorithms.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: True</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_get_session_algorithms")]
public static extern GLib.Internal.NullableUtf8StringUnownedHandle GetSessionAlgorithms(IntPtr self);

/// <summary>
///Calls native method secret_service_get_session_dbus_path.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: True</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_get_session_dbus_path")]
public static extern GLib.Internal.NullableUtf8StringUnownedHandle GetSessionDbusPath(IntPtr self);

/// <summary>
///Calls native method secret_service_load_collections.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_load_collections")]
public static extern void LoadCollections(IntPtr self, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_service_load_collections_finish.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_load_collections_finish")]
public static extern bool LoadCollectionsFinish(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_load_collections_sync.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_load_collections_sync")]
public static extern bool LoadCollectionsSync(IntPtr self, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_lock.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: True</param>
/// <param name="objects">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_lock")]
public static extern void Lock(IntPtr service, GLib.Internal.ListHandle objects, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_service_lock_dbus_paths.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="paths">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_lock_dbus_paths")]
public static extern void LockDbusPaths(IntPtr self, GLib.Internal.Utf8StringArrayNullTerminatedHandle paths, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_service_lock_dbus_paths_finish.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <param name="locked">Transfer ownership: Full Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_lock_dbus_paths_finish")]
public static extern int LockDbusPathsFinish(IntPtr self, IntPtr result, out GLib.Internal.Utf8StringArrayNullTerminatedOwnedHandle locked, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_lock_dbus_paths_sync.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="paths">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="locked">Transfer ownership: Full Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_lock_dbus_paths_sync")]
public static extern int LockDbusPathsSync(IntPtr self, GLib.Internal.Utf8StringArrayNullTerminatedHandle paths, IntPtr cancellable, out GLib.Internal.Utf8StringArrayNullTerminatedOwnedHandle locked, out GLib.Internal.ErrorOwnedHandle error);



/// <summary>
///Calls native method secret_service_lookup.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: True</param>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_lookup")]
public static extern void Lookup(IntPtr service, Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableHandle attributes, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_service_lookup_finish.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: True</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_lookup_finish")]
public static extern Secret.Internal.ValueOwnedHandle LookupFinish(IntPtr service, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_lookup_sync.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: True</param>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_lookup_sync")]
public static extern Secret.Internal.ValueOwnedHandle LookupSync(IntPtr service, Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableHandle attributes, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_prompt.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="prompt">Transfer ownership: None Nullable: False</param>
/// <param name="returnType">Transfer ownership: None Nullable: True</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_prompt")]
public static extern void Prompt(IntPtr self, IntPtr prompt, GLib.Internal.VariantTypeHandle returnType, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_service_prompt_at_dbus_path.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="promptPath">Transfer ownership: None Nullable: False</param>
/// <param name="returnType">Transfer ownership: None Nullable: True</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_prompt_at_dbus_path")]
public static extern void PromptAtDbusPath(IntPtr self, GLib.Internal.NonNullableUtf8StringHandle promptPath, GLib.Internal.VariantTypeHandle returnType, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_service_prompt_at_dbus_path_finish.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: True</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_prompt_at_dbus_path_finish")]
public static extern GLib.Internal.VariantOwnedHandle PromptAtDbusPathFinish(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_prompt_at_dbus_path_sync.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="promptPath">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="returnType">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: Full Nullable: True</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_prompt_at_dbus_path_sync")]
public static extern GLib.Internal.VariantOwnedHandle PromptAtDbusPathSync(IntPtr self, GLib.Internal.NonNullableUtf8StringHandle promptPath, IntPtr cancellable, GLib.Internal.VariantTypeHandle returnType, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_prompt_finish.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_prompt_finish")]
public static extern GLib.Internal.VariantOwnedHandle PromptFinish(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_prompt_sync.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="prompt">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="returnType">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_prompt_sync")]
public static extern GLib.Internal.VariantOwnedHandle PromptSync(IntPtr self, IntPtr prompt, IntPtr cancellable, GLib.Internal.VariantTypeHandle returnType, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_read_alias_dbus_path.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="alias">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_read_alias_dbus_path")]
public static extern void ReadAliasDbusPath(IntPtr self, GLib.Internal.NonNullableUtf8StringHandle alias, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_service_read_alias_dbus_path_finish.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: True</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_read_alias_dbus_path_finish")]
public static extern GLib.Internal.NullableUtf8StringOwnedHandle ReadAliasDbusPathFinish(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_read_alias_dbus_path_sync.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="alias">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: Full Nullable: True</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_read_alias_dbus_path_sync")]
public static extern GLib.Internal.NullableUtf8StringOwnedHandle ReadAliasDbusPathSync(IntPtr self, GLib.Internal.NonNullableUtf8StringHandle alias, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_search.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: True</param>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: None Nullable: False</param>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_search")]
public static extern void Search(IntPtr service, Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableHandle attributes, Secret.SearchFlags flags, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_service_search_finish.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: True</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_search_finish")]
public static extern GLib.Internal.ListOwnedHandle SearchFinish(IntPtr service, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_search_for_dbus_paths.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_search_for_dbus_paths")]
public static extern void SearchForDbusPaths(IntPtr self, Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableHandle attributes, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_service_search_for_dbus_paths_finish.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <param name="unlocked">Transfer ownership: Full Nullable: True</param>
/// <param name="locked">Transfer ownership: Full Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_search_for_dbus_paths_finish")]
public static extern bool SearchForDbusPathsFinish(IntPtr self, IntPtr result, out GLib.Internal.Utf8StringArrayNullTerminatedOwnedHandle unlocked, out GLib.Internal.Utf8StringArrayNullTerminatedOwnedHandle locked, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_search_for_dbus_paths_sync.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="unlocked">Transfer ownership: Full Nullable: True</param>
/// <param name="locked">Transfer ownership: Full Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_search_for_dbus_paths_sync")]
public static extern bool SearchForDbusPathsSync(IntPtr self, Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableHandle attributes, IntPtr cancellable, out GLib.Internal.Utf8StringArrayNullTerminatedOwnedHandle unlocked, out GLib.Internal.Utf8StringArrayNullTerminatedOwnedHandle locked, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_search_sync.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: True</param>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: None Nullable: False</param>
/// <param name="flags">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_search_sync")]
public static extern GLib.Internal.ListOwnedHandle SearchSync(IntPtr service, Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableHandle attributes, Secret.SearchFlags flags, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_set_alias.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: True</param>
/// <param name="alias">Transfer ownership: None Nullable: False</param>
/// <param name="collection">Transfer ownership: None Nullable: True</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_set_alias")]
public static extern void SetAlias(IntPtr service, GLib.Internal.NonNullableUtf8StringHandle alias, IntPtr collection, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_service_set_alias_finish.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: True</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_set_alias_finish")]
public static extern bool SetAliasFinish(IntPtr service, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_set_alias_sync.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: True</param>
/// <param name="alias">Transfer ownership: None Nullable: False</param>
/// <param name="collection">Transfer ownership: None Nullable: True</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_set_alias_sync")]
public static extern bool SetAliasSync(IntPtr service, GLib.Internal.NonNullableUtf8StringHandle alias, IntPtr collection, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_set_alias_to_dbus_path.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="alias">Transfer ownership: None Nullable: False</param>
/// <param name="collectionPath">Transfer ownership: None Nullable: True</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_set_alias_to_dbus_path")]
public static extern void SetAliasToDbusPath(IntPtr self, GLib.Internal.NonNullableUtf8StringHandle alias, GLib.Internal.NullableUtf8StringHandle collectionPath, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_service_set_alias_to_dbus_path_finish.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_set_alias_to_dbus_path_finish")]
public static extern bool SetAliasToDbusPathFinish(IntPtr self, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_set_alias_to_dbus_path_sync.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="alias">Transfer ownership: None Nullable: False</param>
/// <param name="collectionPath">Transfer ownership: None Nullable: True</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_set_alias_to_dbus_path_sync")]
public static extern bool SetAliasToDbusPathSync(IntPtr self, GLib.Internal.NonNullableUtf8StringHandle alias, GLib.Internal.NullableUtf8StringHandle collectionPath, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_store.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: True</param>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: None Nullable: False</param>
/// <param name="collection">Transfer ownership: None Nullable: True</param>
/// <param name="label">Transfer ownership: None Nullable: False</param>
/// <param name="value">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_store")]
public static extern void Store(IntPtr service, Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableHandle attributes, GLib.Internal.NullableUtf8StringHandle collection, GLib.Internal.NonNullableUtf8StringHandle label, Secret.Internal.ValueHandle value, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_service_store_finish.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: True</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_store_finish")]
public static extern bool StoreFinish(IntPtr service, IntPtr result, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_store_sync.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: True</param>
/// <param name="schema">Transfer ownership: None Nullable: True</param>
/// <param name="attributes">Transfer ownership: None Nullable: False</param>
/// <param name="collection">Transfer ownership: None Nullable: True</param>
/// <param name="label">Transfer ownership: None Nullable: False</param>
/// <param name="value">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_store_sync")]
public static extern bool StoreSync(IntPtr service, Secret.Internal.SchemaHandle schema, GLib.Internal.HashTableHandle attributes, GLib.Internal.NullableUtf8StringHandle collection, GLib.Internal.NonNullableUtf8StringHandle label, Secret.Internal.ValueHandle value, IntPtr cancellable, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_unlock.
/// </summary>
/// <param name="service">Transfer ownership: None Nullable: True</param>
/// <param name="objects">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_unlock")]
public static extern void Unlock(IntPtr service, GLib.Internal.ListHandle objects, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_service_unlock_dbus_paths.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="paths">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="callback">Transfer ownership: None Nullable: True</param>
/// <param name="userData">Transfer ownership: None Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_unlock_dbus_paths")]
public static extern void UnlockDbusPaths(IntPtr self, GLib.Internal.Utf8StringArrayNullTerminatedHandle paths, IntPtr cancellable, Gio.Internal.AsyncReadyCallback callback, IntPtr userData);

/// <summary>
///Calls native method secret_service_unlock_dbus_paths_finish.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="result">Transfer ownership: None Nullable: False</param>
/// <param name="unlocked">Transfer ownership: Full Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_unlock_dbus_paths_finish")]
public static extern int UnlockDbusPathsFinish(IntPtr self, IntPtr result, out GLib.Internal.Utf8StringArrayNullTerminatedOwnedHandle unlocked, out GLib.Internal.ErrorOwnedHandle error);

/// <summary>
///Calls native method secret_service_unlock_dbus_paths_sync.
/// </summary>
/// <param name="self">Transfer ownership: None Nullable: False</param>
/// <param name="paths">Transfer ownership: None Nullable: False</param>
/// <param name="cancellable">Transfer ownership: None Nullable: True</param>
/// <param name="unlocked">Transfer ownership: Full Nullable: True</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_service_unlock_dbus_paths_sync")]
public static extern int UnlockDbusPathsSync(IntPtr self, GLib.Internal.Utf8StringArrayNullTerminatedHandle paths, IntPtr cancellable, out GLib.Internal.Utf8StringArrayNullTerminatedOwnedHandle unlocked, out GLib.Internal.ErrorOwnedHandle error);


    
}