using System;
using GObject;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY


public abstract class ServiceClassHandle : SafeHandle
{    
    public sealed override bool IsInvalid => handle == IntPtr.Zero;

    protected ServiceClassHandle(bool ownsHandle) : base(IntPtr.Zero, ownsHandle) { }

    public Gio.Internal.DBusProxyClassData GetParentClass()
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    return Marshal.PtrToStructure<ServiceClassData>(handle).ParentClass;
}

public nuint GetCollectionGtype()
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    return Marshal.PtrToStructure<ServiceClassData>(handle).CollectionGtype;
}

public nuint GetItemGtype()
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    return Marshal.PtrToStructure<ServiceClassData>(handle).ItemGtype;
}

public ServiceClassData.PromptSyncCallback GetPromptSync()
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    return Marshal.PtrToStructure<ServiceClassData>(handle).PromptSync;
}

public ServiceClassData.PromptAsyncCallback GetPromptAsync()
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    return Marshal.PtrToStructure<ServiceClassData>(handle).PromptAsync;
}

public ServiceClassData.PromptFinishCallback GetPromptFinish()
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    return Marshal.PtrToStructure<ServiceClassData>(handle).PromptFinish;
}

public ServiceClassData.GetCollectionGtypeCallback GetGetCollectionGtype()
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    return Marshal.PtrToStructure<ServiceClassData>(handle).GetCollectionGtype;
}

public ServiceClassData.GetItemGtypeCallback GetGetItemGtype()
{
    if (IsClosed || IsInvalid)
        throw new InvalidOperationException("Handle is closed or invalid");

    return Marshal.PtrToStructure<ServiceClassData>(handle).GetItemGtype;
}



    public bool Equals(ServiceClassHandle? other)
    {
        if (ReferenceEquals(null, other))
            return false;

        if (ReferenceEquals(this, other))
            return true;

        return handle.Equals(other.handle);
    }

    public override bool Equals(object? obj)
    {
        return ReferenceEquals(this, obj) || obj is ServiceClassHandle other && Equals(other);
    }

    public override int GetHashCode()
    {
        return handle.GetHashCode();
    }
}

public class ServiceClassUnownedHandle : ServiceClassHandle
{
    private static ServiceClassUnownedHandle? nullHandle;
    public static ServiceClassUnownedHandle NullHandle => nullHandle ??= new ServiceClassUnownedHandle();

    /// <summary>
    /// Creates a new instance of ServiceClassUnownedHandle. Used automatically by PInvoke.
    /// </summary>
    internal ServiceClassUnownedHandle() : base(false) { }

    /// <summary>
    /// Creates a new instance of ServiceClassOwnedHandle. Assumes that the given pointer is unowned by the runtime.
    /// </summary>
    public ServiceClassUnownedHandle(IntPtr ptr) : base(false)
    {
        SetHandle(ptr);
    }

    public ServiceClassOwnedHandle Copy()
    {
        var size = Marshal.SizeOf<ServiceClassData>();
        var ptr = GLib.Functions.Memdup2(handle,(nuint) size);
            
        return new ServiceClassOwnedHandle(ptr);
    }

    protected override bool ReleaseHandle()
    {
        throw new System.Exception("UnownedHandle must not be freed");
    }
}

public class ServiceClassOwnedHandle : ServiceClassHandle
{
    /// <summary>
    /// Creates a new instance of ServiceClassOwnedHandle. Used automatically by PInvoke.
    /// </summary>
    internal ServiceClassOwnedHandle() : base(true) { }

    /// <summary>
    /// Creates a new instance of ServiceClassOwnedHandle. Assumes that the given pointer is owned by the runtime.
    /// </summary>
    public ServiceClassOwnedHandle(IntPtr ptr) : base(true)
    {
        SetHandle(ptr);
    }

    /// <summary>
    /// Creates a new owned Handle
    /// </summary>
    public static ServiceClassOwnedHandle Create()
    {
        var size = Marshal.SizeOf<ServiceClassData>();
        var ptr = GLib.Functions.Malloc((nuint)size);
       
        var str = new ServiceClassData();
        Marshal.StructureToPtr(str, ptr, false);
            
        return new ServiceClassOwnedHandle(ptr);
    }

    public unsafe void CopyTo(IntPtr ptr)
    {
        var data = Marshal.PtrToStructure<ServiceClassData>(handle);
        Marshal.StructureToPtr(data, ptr, false);
    }

    public ServiceClassUnownedHandle UnownedCopy()
    {
        var size = Marshal.SizeOf<ServiceClassData>();
        var ptr = GLib.Functions.Memdup2(handle,(nuint) size);
            
        return new ServiceClassUnownedHandle(ptr);
    }

    protected override bool ReleaseHandle()
    {
        GLib.Functions.Free(handle);
        return true;
    }
}

public abstract class ServiceClassArrayHandle : SafeHandle
{
    public sealed override bool IsInvalid => handle == IntPtr.Zero;

    protected ServiceClassArrayHandle(bool ownsHandle) : base(IntPtr.Zero, ownsHandle) { }
}

public class ServiceClassArrayUnownedHandle : ServiceClassArrayHandle
{
    private static ServiceClassArrayUnownedHandle? nullHandle;
    public static ServiceClassArrayUnownedHandle NullHandle => nullHandle ??= new ServiceClassArrayUnownedHandle();
    
    private int length;

    /// <summary>
    /// Creates a new instance of ServiceClassArrayUnownedHandle. Used automatically by PInvoke.
    /// </summary>
    internal ServiceClassArrayUnownedHandle() : base(false) { }
    
    public ServiceClassArrayUnownedHandle(IntPtr ptr, int length) : base(false)
    {
        this.length = length;
        SetHandle(ptr);
    }

    public Secret.ServiceClass[] ToArray(int length)
    {
        return ToNullableArray(length) ?? throw new InvalidOperationException("Handle is invalid");
    }

    public Secret.ServiceClass[]? ToNullableArray(int length)
    {
        if (IsInvalid)
            return null;
        
        var data = new Secret.ServiceClass[length];
        var currentHandle = handle;
        for(int i = 0; i < length; i++)
        {
            var ownedHandle = new Secret.Internal.ServiceClassUnownedHandle(currentHandle).Copy();
            data[i] = new Secret.ServiceClass(ownedHandle);
            currentHandle += Marshal.SizeOf<Secret.Internal.ServiceClassData>();
        }

        return data;
    }

    protected override bool ReleaseHandle()
    {
        throw new System.Exception("UnownedHandle must not be freed");
    }
}

public class ServiceClassArrayOwnedHandle : ServiceClassArrayHandle
{
    
    //This has no constructor without parameters as we can't supply a length to an array via pinvoke.
    //The length would need to be set manually and the instance be freed via glib.

    private ServiceClassArrayOwnedHandle(IntPtr ptr) : base(true)
    {
        SetHandle(ptr);
    }

    public static ServiceClassArrayOwnedHandle Create(Secret.ServiceClass[] data)
    {
        var size = Marshal.SizeOf<Secret.Internal.ServiceClassData>();
        var ptr = Marshal.AllocHGlobal(size * data.Length);
        var current = ptr;
        for (int i = 0; i < data.Length; i++)
        {
            var structure = Marshal.PtrToStructure<Secret.Internal.ServiceClassData>(data[i].Handle.DangerousGetHandle());
            Marshal.StructureToPtr(structure, current, false);
            current += size;
        }
        
        return new ServiceClassArrayOwnedHandle(ptr);
    }
    
    protected override bool ReleaseHandle()
    {
        Marshal.FreeHGlobal(handle);
        return true;
    }
}