
using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret.Internal;

// AUTOGENERATED FILE - DO NOT MODIFY


public partial class Value
{
    
/// <summary>
///Calls native constructor secret_value_new.
/// </summary>
/// <param name="secret">Transfer ownership: None Nullable: False</param>
/// <param name="length">Transfer ownership: None Nullable: False</param>
/// <param name="contentType">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_value_new")]
public static extern Secret.Internal.ValueOwnedHandle New(GLib.Internal.NonNullableUtf8StringHandle secret, nint length, GLib.Internal.NonNullableUtf8StringHandle contentType);

/// <summary>
///Calls native constructor secret_value_new_full.
/// </summary>
/// <param name="secret">Transfer ownership: None Nullable: False</param>
/// <param name="length">Transfer ownership: None Nullable: False</param>
/// <param name="contentType">Transfer ownership: None Nullable: False</param>
/// <param name="destroy">Transfer ownership: None Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_value_new_full")]
public static extern Secret.Internal.ValueOwnedHandle NewFull(GLib.Internal.NonNullableUtf8StringHandle secret, nint length, GLib.Internal.NonNullableUtf8StringHandle contentType, GLib.Internal.DestroyNotify destroy);
    
/// <summary>
///Calls native function secret_value_get_type.
/// </summary>

/// <returns>Transfer ownership: None Nullable: False</returns>


[DllImport(ImportResolver.Library, EntryPoint = "secret_value_get_type")]
public static extern nuint GetGType();
    
    
/// <summary>
///Calls native method secret_value_get.
/// </summary>
/// <param name="value">Transfer ownership: None Nullable: False</param>
/// <param name="length">Transfer ownership: Full Nullable: False</param>
/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_value_get")]
public static extern byte[] Get(Secret.Internal.ValueHandle value, out nuint length);

/// <summary>
///Calls native method secret_value_get_content_type.
/// </summary>
/// <param name="value">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_value_get_content_type")]
public static extern GLib.Internal.NonNullableUtf8StringUnownedHandle GetContentType(Secret.Internal.ValueHandle value);

/// <summary>
///Calls native method secret_value_get_text.
/// </summary>
/// <param name="value">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: True</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_value_get_text")]
public static extern GLib.Internal.NullableUtf8StringUnownedHandle GetText(Secret.Internal.ValueHandle value);

/// <summary>
///Calls native method secret_value_ref.
/// </summary>
/// <param name="value">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: Full Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_value_ref")]
public static extern Secret.Internal.ValueOwnedHandle Ref(Secret.Internal.ValueHandle value);

/// <summary>
///Calls native method secret_value_unref.
/// </summary>
/// <param name="value">Transfer ownership: None Nullable: False</param>

/// <returns>Transfer ownership: None Nullable: False</returns>

[DllImport(ImportResolver.Library, EntryPoint = "secret_value_unref")]
public static extern void Unref(Secret.Internal.ValueHandle value);

/// <summary>
///Calls native method secret_value_unref_to_password.
///Version: 0.19.0
/// </summary>
/// <param name="value">Transfer ownership: None Nullable: False</param>
/// <param name="length">Transfer ownership: Full Nullable: False</param>
/// <returns>Transfer ownership: Full Nullable: False</returns>
[Version("0.19.0")]
[DllImport(ImportResolver.Library, EntryPoint = "secret_value_unref_to_password")]
public static extern GLib.Internal.NonNullableUtf8StringOwnedHandle UnrefToPassword(Secret.Internal.ValueHandle value, ref nuint length);
}