
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Rsvg;

// AUTOGENERATED FILE - DO NOT MODIFY

public partial class Constants
{
    

public const bool HAVE_CSS = true;


public const int HAVE_PIXBUF = 1;


public const bool HAVE_SVGZ = true;


public const int MAJOR_VERSION = 2;


public const int MICRO_VERSION = 0;


public const int MINOR_VERSION = 60;


public const string VERSION = "2.60.0";
}