
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Rsvg;

// AUTOGENERATED FILE - DO NOT MODIFY


public sealed partial class DimensionData
{
    public Rsvg.Internal.DimensionDataOwnedHandle Handle { get; }

    public DimensionData(Rsvg.Internal.DimensionDataOwnedHandle handle)
    {
        Handle = handle;
    }

    public DimensionData() : this(Rsvg.Internal.DimensionDataOwnedHandle.Create())
    {
    }

    

    public int Width {
get => Handle.GetWidth();
set => Handle.SetWidth(value);
}

public int Height {
get => Handle.GetHeight();
set => Handle.SetHeight(value);
}

public double Em {
get => Handle.GetEm();
set => Handle.SetEm(value);
}

public double Ex {
get => Handle.GetEx();
set => Handle.SetEx(value);
}


    

    

    public bool Equals(DimensionData? other)
    {
        if (ReferenceEquals(null, other))
            return false;

        if (ReferenceEquals(this, other))
            return true;

        return Handle.Equals(other.Handle);
    }

    public override bool Equals(object? obj)
    {
        return ReferenceEquals(this, obj) || obj is DimensionData other && Equals(other);
    }

    public override int GetHashCode()
    {
        return Handle.GetHashCode();
    }
}