
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Rsvg;

// AUTOGENERATED FILE - DO NOT MODIFY


[GObject.Handle<Rsvg.Internal.HandleHandle>]
public partial class Handle(Rsvg.Internal.HandleHandle handle) : GObject.Object(handle)
{
       public Handle(params GObject.ConstructArgument[] constructArguments) : this(Rsvg.Internal.HandleHandle.For<Handle>(constructArguments)) { }
}