
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Rsvg;

// AUTOGENERATED FILE - DO NOT MODIFY


[Flags]
public enum HandleFlags : uint
{
    FlagsNone = 0,
FlagUnlimited = 1,
FlagKeepImageData = 2,
}