
using System;
using System.Linq;
using GObject;
using System.Runtime.InteropServices;

#nullable enable

namespace Rsvg;

// AUTOGENERATED FILE - DO NOT MODIFY

public partial class Handle
{
    

public static Handle New()
{
    
    var handleHandle = Internal.Handle.New();
return Rsvg.Handle.CreateIntern(handleHandle, true);

}

[Version("2.14")]
public static Handle? NewFromData(Span<byte> data)
{
    
    var handleHandle = Internal.Handle.NewFromData(ref MemoryMarshal.GetReference(data), (nuint) data.Length, out GLib.Internal.ErrorOwnedHandle error);
if(!error.IsInvalid)
    throw new GLib.GException(error);return Rsvg.Handle.CreateIntern(handleHandle, true);

}

[Version("2.14")]
public static Handle? NewFromFile(string filename)
{
    using var filenameNative = GLib.Internal.NonNullableUtf8StringOwnedHandle.Create(filename);
    var handleHandle = Internal.Handle.NewFromFile(filenameNative, out GLib.Internal.ErrorOwnedHandle error);
if(!error.IsInvalid)
    throw new GLib.GException(error);return Rsvg.Handle.CreateIntern(handleHandle, true);

}

[Version("2.32")]
public static Handle? NewFromGfileSync(Gio.File file, Rsvg.HandleFlags flags, Gio.Cancellable? cancellable)
{
    
    var handleHandle = Internal.Handle.NewFromGfileSync(((GObject.Object)file).Handle.DangerousGetHandle(), flags, cancellable?.Handle.DangerousGetHandle() ?? IntPtr.Zero, out GLib.Internal.ErrorOwnedHandle error);
if(!error.IsInvalid)
    throw new GLib.GException(error);return Rsvg.Handle.CreateIntern(handleHandle, true);

}

[Version("2.32")]
public static Handle? NewFromStreamSync(Gio.InputStream inputStream, Gio.File? baseFile, Rsvg.HandleFlags flags, Gio.Cancellable? cancellable)
{
    
    var handleHandle = Internal.Handle.NewFromStreamSync(inputStream.Handle.DangerousGetHandle(), ((GObject.Object?)baseFile)?.Handle.DangerousGetHandle() ?? IntPtr.Zero, flags, cancellable?.Handle.DangerousGetHandle() ?? IntPtr.Zero, out GLib.Internal.ErrorOwnedHandle error);
if(!error.IsInvalid)
    throw new GLib.GException(error);return Rsvg.Handle.CreateIntern(handleHandle, true);

}

[Version("2.36")]
public static Handle NewWithFlags(Rsvg.HandleFlags flags)
{
    
    var handleHandle = Internal.Handle.NewWithFlags(flags);
return Rsvg.Handle.CreateIntern(handleHandle, true);

}
}