
using System;
using System.Linq;
using GObject;
using System.Runtime.InteropServices;

#nullable enable

namespace Rsvg;

// AUTOGENERATED FILE - DO NOT MODIFY

public partial class Handle : GObject.GTypeProvider, GObject.InstanceFactory
{

    public static new GObject.Type GetGType()
    {
        return Rsvg.Internal.Handle.GetGType();
    }

    static object GObject.InstanceFactory.Create(IntPtr handle, bool ownsHandle)
    {
        return CreateIntern(handle, ownsHandle);
    }

    private static Handle CreateIntern(IntPtr handle, bool ownsHandle)
    {
        return new Handle(new Rsvg.Internal.HandleHandle(handle, ownsHandle));
    }

    
}