
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Rsvg;

// AUTOGENERATED FILE - DO NOT MODIFY


public sealed partial class HandleClass
{
    public Rsvg.Internal.HandleClassOwnedHandle Handle { get; }

    public HandleClass(Rsvg.Internal.HandleClassOwnedHandle handle)
    {
        Handle = handle;
    }

    public HandleClass() : this(Rsvg.Internal.HandleClassOwnedHandle.Create())
    {
    }

    

    


    

    

    public bool Equals(HandleClass? other)
    {
        if (ReferenceEquals(null, other))
            return false;

        if (ReferenceEquals(this, other))
            return true;

        return Handle.Equals(other.Handle);
    }

    public override bool Equals(object? obj)
    {
        return ReferenceEquals(this, obj) || obj is HandleClass other && Equals(other);
    }

    public override int GetHashCode()
    {
        return Handle.GetHashCode();
    }
}