
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Rsvg;

// AUTOGENERATED FILE - DO NOT MODIFY


public sealed partial class Length
{
    public Rsvg.Internal.LengthOwnedHandle Handle { get; }

    public Length(Rsvg.Internal.LengthOwnedHandle handle)
    {
        Handle = handle;
    }

    public Length() : this(Rsvg.Internal.LengthOwnedHandle.Create())
    {
    }



    public double Lengths
    {
        get => Handle.GetLength();
        set => Handle.SetLength(value);
    }

    public Rsvg.Unit Unit
    {
        get => Handle.GetUnit();
        set => Handle.SetUnit(value);
    }






    public bool Equals(Length? other)
    {
        if (ReferenceEquals(null, other))
            return false;

        if (ReferenceEquals(this, other))
            return true;

        return Handle.Equals(other.Handle);
    }

    public override bool Equals(object? obj)
    {
        return ReferenceEquals(this, obj) || obj is Length other && Equals(other);
    }

    public override int GetHashCode()
    {
        return Handle.GetHashCode();
    }
}
