
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Rsvg;

// AUTOGENERATED FILE - DO NOT MODIFY


public sealed partial class PositionData
{
    public Rsvg.Internal.PositionDataOwnedHandle Handle { get; }

    public PositionData(Rsvg.Internal.PositionDataOwnedHandle handle)
    {
        Handle = handle;
    }

    public PositionData() : this(Rsvg.Internal.PositionDataOwnedHandle.Create())
    {
    }

    

    public int X {
get => Handle.GetX();
set => Handle.SetX(value);
}

public int Y {
get => Handle.GetY();
set => Handle.SetY(value);
}


    

    

    public bool Equals(PositionData? other)
    {
        if (ReferenceEquals(null, other))
            return false;

        if (ReferenceEquals(this, other))
            return true;

        return Handle.Equals(other.Handle);
    }

    public override bool Equals(object? obj)
    {
        return ReferenceEquals(this, obj) || obj is PositionData other && Equals(other);
    }

    public override int GetHashCode()
    {
        return Handle.GetHashCode();
    }
}