
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Rsvg;

// AUTOGENERATED FILE - DO NOT MODIFY


public sealed partial class Rectangle
{
    public Rsvg.Internal.RectangleOwnedHandle Handle { get; }

    public Rectangle(Rsvg.Internal.RectangleOwnedHandle handle)
    {
        Handle = handle;
    }

    public Rectangle() : this(Rsvg.Internal.RectangleOwnedHandle.Create())
    {
    }

    

    public double X {
get => Handle.GetX();
set => Handle.SetX(value);
}

public double Y {
get => Handle.GetY();
set => Handle.SetY(value);
}

public double Width {
get => Handle.GetWidth();
set => Handle.SetWidth(value);
}

public double Height {
get => Handle.GetHeight();
set => Handle.SetHeight(value);
}


    

    

    public bool Equals(Rectangle? other)
    {
        if (ReferenceEquals(null, other))
            return false;

        if (ReferenceEquals(this, other))
            return true;

        return Handle.Equals(other.Handle);
    }

    public override bool Equals(object? obj)
    {
        return ReferenceEquals(this, obj) || obj is Rectangle other && Equals(other);
    }

    public override int GetHashCode()
    {
        return Handle.GetHashCode();
    }
}