
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Rsvg;

// AUTOGENERATED FILE - DO NOT MODIFY


public enum Unit : int
{
    Percent = 0,
Px = 1,
Em = 2,
Ex = 3,
In = 4,
Cm = 5,
Mm = 6,
Pt = 7,
Pc = 8,
Ch = 9,
}