
using System;
using GObject;
using System.Runtime.InteropServices;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY

public partial class BackendHelper
{
    public Secret.ServiceFlags Flags
{
    get => Secret.Backend.FlagsPropertyDefinition.Get(this);
}


}