
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY


public sealed partial class BackendInterface
{
    public Secret.Internal.BackendInterfaceOwnedHandle Handle { get; }

    public BackendInterface(Secret.Internal.BackendInterfaceOwnedHandle handle)
    {
        Handle = handle;
    }

    public BackendInterface() : this(Secret.Internal.BackendInterfaceOwnedHandle.Create())
    {
    }

    

    











    

    

    public bool Equals(BackendInterface? other)
    {
        if (ReferenceEquals(null, other))
            return false;

        if (ReferenceEquals(this, other))
            return true;

        return Handle.Equals(other.Handle);
    }

    public override bool Equals(object? obj)
    {
        return ReferenceEquals(this, obj) || obj is BackendInterface other && Equals(other);
    }

    public override int GetHashCode()
    {
        return Handle.GetHashCode();
    }
}