
using System;
using GObject;
using GObject.Internal;
using System.Runtime.InteropServices;

#nullable enable

namespace Secret
{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial interface Backend
    {
        ObjectHandle Handle { get; }
        
        public static readonly Property<Secret.ServiceFlags, Backend> FlagsPropertyDefinition = new (
    unmanagedName: "flags",
    managedName: nameof(Flags)
);

public Secret.ServiceFlags Flags { get; }

    }
}