
using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY


public sealed partial class BackendHelper : GObject.Object, Backend, GObject.InstanceFactory
{
    public BackendHelper(GObject.Internal.ObjectHandle handle) : base(handle)
    {
    }

    static object GObject.InstanceFactory.Create(IntPtr handle, bool ownsHandle)
    {
        return new BackendHelper(new GObject.Internal.ObjectHandle(handle, ownsHandle));
    }
}