
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY


public sealed partial class CollectionClass
{
    public Secret.Internal.CollectionClassOwnedHandle Handle { get; }

    public CollectionClass(Secret.Internal.CollectionClassOwnedHandle handle)
    {
        Handle = handle;
    }

    public CollectionClass() : this(Secret.Internal.CollectionClassOwnedHandle.Create())
    {
    }

    

    


    

    

    public bool Equals(CollectionClass? other)
    {
        if (ReferenceEquals(null, other))
            return false;

        if (ReferenceEquals(this, other))
            return true;

        return Handle.Equals(other.Handle);
    }

    public override bool Equals(object? obj)
    {
        return ReferenceEquals(this, obj) || obj is CollectionClass other && Equals(other);
    }

    public override int GetHashCode()
    {
        return Handle.GetHashCode();
    }
}