
using System;
using System.Linq;
using GObject;
using System.Runtime.InteropServices;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY

public partial class Collection
{
    

public static Collection NewForDbusPathFinish(Gio.AsyncResult result)
{
    
    var collectionHandle = Internal.Collection.NewForDbusPathFinish(((GObject.Object)result).Handle.DangerousGetHandle(), out GLib.Internal.ErrorOwnedHandle error);
if(!error.IsInvalid)
    throw new GLib.GException(error);return Secret.Collection.CreateIntern(collectionHandle, true);

}


public static Collection NewForDbusPathSync(Secret.Service? service, string collectionPath, Secret.CollectionFlags flags, Gio.Cancellable? cancellable)
{
    using var collectionPathNative = GLib.Internal.NonNullableUtf8StringOwnedHandle.Create(collectionPath);
    var collectionHandle = Internal.Collection.NewForDbusPathSync(service?.Handle.DangerousGetHandle() ?? IntPtr.Zero, collectionPathNative, flags, cancellable?.Handle.DangerousGetHandle() ?? IntPtr.Zero, out GLib.Internal.ErrorOwnedHandle error);
if(!error.IsInvalid)
    throw new GLib.GException(error);return Secret.Collection.CreateIntern(collectionHandle, true);

}
}