
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY


[GObject.Handle<Secret.Internal.CollectionHandle>]
public partial class Collection(Secret.Internal.CollectionHandle handle) : Gio.DBusProxy(handle), Gio.AsyncInitable, Gio.DBusInterface, Gio.Initable
{
       public Collection(params GObject.ConstructArgument[] constructArguments) : this(Secret.Internal.CollectionHandle.For<Collection>(constructArguments)) { }
}