
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY

public partial class Constants
{
    

public const string BACKEND_EXTENSION_POINT_NAME = "secret-backend";


public const string COLLECTION_DEFAULT = "default";


public const string COLLECTION_SESSION = "session";


public const int MAJOR_VERSION = 0;


public const int MICRO_VERSION = 7;


public const int MINOR_VERSION = 21;
}