
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY


public enum Error : int
{
    Protocol = 1,
IsLocked = 2,
NoSuchObject = 3,
AlreadyExists = 4,
InvalidFileFormat = 5,
MismatchedSchema = 6,
NoMatchingAttribute = 7,
WrongType = 8,
EmptyTable = 9,
}