
using System;
using System.Linq;
using GObject;
using System.Runtime.InteropServices;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY

public partial class Item
{
    

[Version("2.22")]
public bool InitFinish(Gio.AsyncResult res)
{
    
    var resultInitFinish = Gio.Internal.AsyncInitable.InitFinish(this.Handle.DangerousGetHandle(), ((GObject.Object)res).Handle.DangerousGetHandle(), out GLib.Internal.ErrorOwnedHandle error);
if(!error.IsInvalid)
    throw new GLib.GException(error);
    
    
    return resultInitFinish;
}

[Version("2.22")]
GObject.Object Gio.AsyncInitable.NewFinish(Gio.AsyncResult res)
{
    
    var resultNewFinish = Gio.Internal.AsyncInitable.NewFinish(this.Handle.DangerousGetHandle(), ((GObject.Object)res).Handle.DangerousGetHandle(), out GLib.Internal.ErrorOwnedHandle error);
if(!error.IsInvalid)
    throw new GLib.GException(error);
    
    
    return (GObject.Object) GObject.Internal.InstanceWrapper.WrapHandle<GObject.Object>(resultNewFinish, true);
}

[Version("2.32")]
public Gio.DBusObject? DupObject()
{
    
    var resultDupObject = Gio.Internal.DBusInterface.DupObject(this.Handle.DangerousGetHandle());

    
    
    return (Gio.DBusObject?) GObject.Internal.InstanceWrapper.WrapNullableHandle<Gio.DBusObjectHelper>(resultDupObject, true);
}

[Version("2.30")]
Gio.DBusInterfaceInfo Gio.DBusInterface.GetInfo()
{
    
    var resultGetInfo = Gio.Internal.DBusInterface.GetInfo(this.Handle.DangerousGetHandle());

    
    
    return new Gio.DBusInterfaceInfo(resultGetInfo.OwnedCopy());
}

[Version("2.30")]
public Gio.DBusObject? GetObject()
{
    
    var resultGetObject = Gio.Internal.DBusInterface.GetObject(this.Handle.DangerousGetHandle());

    
    
    return (Gio.DBusObject?) GObject.Internal.InstanceWrapper.WrapNullableHandle<Gio.DBusObjectHelper>(resultGetObject, false);
}

[Version("2.30")]
public void SetObject(Gio.DBusObject? @object)
{
    
    Gio.Internal.DBusInterface.SetObject(this.Handle.DangerousGetHandle(), ((GObject.Object?)@object)?.Handle.DangerousGetHandle() ?? IntPtr.Zero);

    
    
    
}

[Version("2.22")]
public bool Init(Gio.Cancellable? cancellable)
{
    
    var resultInit = Gio.Internal.Initable.Init(this.Handle.DangerousGetHandle(), cancellable?.Handle.DangerousGetHandle() ?? IntPtr.Zero, out GLib.Internal.ErrorOwnedHandle error);
if(!error.IsInvalid)
    throw new GLib.GException(error);
    
    
    return resultInit;
}

[Version("0.19.0")]
GLib.HashTable Secret.Retrievable.GetAttributes()
{
    
    var resultGetAttributes = Secret.Internal.Retrievable.GetAttributes(this.Handle.DangerousGetHandle());

    
    
    return new GLib.HashTable(resultGetAttributes);
}

[Version("0.19.0")]
ulong Secret.Retrievable.GetCreated()
{
    
    var resultGetCreated = Secret.Internal.Retrievable.GetCreated(this.Handle.DangerousGetHandle());

    
    
    return resultGetCreated;
}

[Version("0.19.0")]
string Secret.Retrievable.GetLabel()
{
    
    var resultGetLabel = Secret.Internal.Retrievable.GetLabel(this.Handle.DangerousGetHandle());

    
    
    return resultGetLabel.ConvertToString();
}

[Version("0.19.0")]
ulong Secret.Retrievable.GetModified()
{
    
    var resultGetModified = Secret.Internal.Retrievable.GetModified(this.Handle.DangerousGetHandle());

    
    
    return resultGetModified;
}


[Version("0.19.0")]
public Secret.Value? RetrieveSecretFinish(Gio.AsyncResult result)
{
    
    var resultRetrieveSecretFinish = Secret.Internal.Retrievable.RetrieveSecretFinish(this.Handle.DangerousGetHandle(), ((GObject.Object)result).Handle.DangerousGetHandle(), out GLib.Internal.ErrorOwnedHandle error);
if(!error.IsInvalid)
    throw new GLib.GException(error);
    
    
    return resultRetrieveSecretFinish.IsInvalid ? null : new Secret.Value(resultRetrieveSecretFinish);
}

[Version("0.19.0")]
public Secret.Value? RetrieveSecretSync(Gio.Cancellable? cancellable)
{
    
    var resultRetrieveSecretSync = Secret.Internal.Retrievable.RetrieveSecretSync(this.Handle.DangerousGetHandle(), cancellable?.Handle.DangerousGetHandle() ?? IntPtr.Zero, out GLib.Internal.ErrorOwnedHandle error);
if(!error.IsInvalid)
    throw new GLib.GException(error);
    
    
    return resultRetrieveSecretSync.IsInvalid ? null : new Secret.Value(resultRetrieveSecretSync);
}
}