
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY


[GObject.Handle<Secret.Internal.ItemHandle>]
public partial class Item(Secret.Internal.ItemHandle handle) : Gio.DBusProxy(handle), Gio.AsyncInitable, Gio.DBusInterface, Gio.Initable, Secret.Retrievable
{
       public Item(params GObject.ConstructArgument[] constructArguments) : this(Secret.Internal.ItemHandle.For<Item>(constructArguments)) { }
}