
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY


[Flags]
public enum ItemCreateFlags : uint
{
    None = 0,
Replace = 2,
}