
using System;
using System.Linq;
using GObject;
using System.Runtime.InteropServices;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY

public partial class Item
{
    

public static Item NewForDbusPathFinish(Gio.AsyncResult result)
{
    
    var itemHandle = Internal.Item.NewForDbusPathFinish(((GObject.Object)result).Handle.DangerousGetHandle(), out GLib.Internal.ErrorOwnedHandle error);
if(!error.IsInvalid)
    throw new GLib.GException(error);return Secret.Item.CreateIntern(itemHandle, true);

}


public static Item NewForDbusPathSync(Secret.Service? service, string itemPath, Secret.ItemFlags flags, Gio.Cancellable? cancellable)
{
    using var itemPathNative = GLib.Internal.NonNullableUtf8StringOwnedHandle.Create(itemPath);
    var itemHandle = Internal.Item.NewForDbusPathSync(service?.Handle.DangerousGetHandle() ?? IntPtr.Zero, itemPathNative, flags, cancellable?.Handle.DangerousGetHandle() ?? IntPtr.Zero, out GLib.Internal.ErrorOwnedHandle error);
if(!error.IsInvalid)
    throw new GLib.GException(error);return Secret.Item.CreateIntern(itemHandle, true);

}
}