
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY


public sealed partial class ItemClass
{
    public Secret.Internal.ItemClassOwnedHandle Handle { get; }

    public ItemClass(Secret.Internal.ItemClassOwnedHandle handle)
    {
        Handle = handle;
    }

    public ItemClass() : this(Secret.Internal.ItemClassOwnedHandle.Create())
    {
    }

    

    


    

    

    public bool Equals(ItemClass? other)
    {
        if (ReferenceEquals(null, other))
            return false;

        if (ReferenceEquals(this, other))
            return true;

        return Handle.Equals(other.Handle);
    }

    public override bool Equals(object? obj)
    {
        return ReferenceEquals(this, obj) || obj is ItemClass other && Equals(other);
    }

    public override int GetHashCode()
    {
        return Handle.GetHashCode();
    }
}