
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY


public sealed partial class PromptPrivate 
{
    public Secret.Internal.PromptPrivateOwnedHandle Handle { get; }

    public PromptPrivate(Secret.Internal.PromptPrivateOwnedHandle handle)
    {
        Handle = handle;
        Initialize();
    }

    // Implement this to perform additional steps in the constructor
    partial void Initialize();

    

    

    

    public bool Equals(PromptPrivate? other)
    {
        if (ReferenceEquals(null, other))
            return false;

        if (ReferenceEquals(this, other))
            return true;

        return Handle.Equals(other.Handle);
    }

    public override bool Equals(object? obj)
    {
        return ReferenceEquals(this, obj) || obj is PromptPrivate other && Equals(other);
    }

    public override int GetHashCode()
    {
        return Handle.GetHashCode();
    }

    
}