
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY


public sealed partial class PromptClass
{
    public Secret.Internal.PromptClassOwnedHandle Handle { get; }

    public PromptClass(Secret.Internal.PromptClassOwnedHandle handle)
    {
        Handle = handle;
    }

    public PromptClass() : this(Secret.Internal.PromptClassOwnedHandle.Create())
    {
    }

    

    


    

    

    public bool Equals(PromptClass? other)
    {
        if (ReferenceEquals(null, other))
            return false;

        if (ReferenceEquals(this, other))
            return true;

        return Handle.Equals(other.Handle);
    }

    public override bool Equals(object? obj)
    {
        return ReferenceEquals(this, obj) || obj is PromptClass other && Equals(other);
    }

    public override int GetHashCode()
    {
        return Handle.GetHashCode();
    }
}