
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY


[GObject.Handle<Secret.Internal.PromptHandle>]
public partial class Prompt(Secret.Internal.PromptHandle handle) : Gio.DBusProxy(handle), Gio.AsyncInitable, Gio.DBusInterface, Gio.Initable
{
       public Prompt(params GObject.ConstructArgument[] constructArguments) : this(Secret.Internal.PromptHandle.For<Prompt>(constructArguments)) { }
}