
using System;
using System.Linq;
using GObject;
using System.Runtime.InteropServices;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY

public partial class RetrievableHelper
{
    
[Version("0.19.0")]
GLib.HashTable Secret.Retrievable.GetAttributes()
{
    
    var resultGetAttributes = Secret.Internal.Retrievable.GetAttributes(this.Handle.DangerousGetHandle());

    
    
    return new GLib.HashTable(resultGetAttributes);
}

[Version("0.19.0")]
ulong Secret.Retrievable.GetCreated()
{
    
    var resultGetCreated = Secret.Internal.Retrievable.GetCreated(this.Handle.DangerousGetHandle());

    
    
    return resultGetCreated;
}

[Version("0.19.0")]
string Secret.Retrievable.GetLabel()
{
    
    var resultGetLabel = Secret.Internal.Retrievable.GetLabel(this.Handle.DangerousGetHandle());

    
    
    return resultGetLabel.ConvertToString();
}

[Version("0.19.0")]
ulong Secret.Retrievable.GetModified()
{
    
    var resultGetModified = Secret.Internal.Retrievable.GetModified(this.Handle.DangerousGetHandle());

    
    
    return resultGetModified;
}


[Version("0.19.0")]
public Secret.Value? RetrieveSecretFinish(Gio.AsyncResult result)
{
    
    var resultRetrieveSecretFinish = Secret.Internal.Retrievable.RetrieveSecretFinish(this.Handle.DangerousGetHandle(), ((GObject.Object)result).Handle.DangerousGetHandle(), out GLib.Internal.ErrorOwnedHandle error);
if(!error.IsInvalid)
    throw new GLib.GException(error);
    
    
    return resultRetrieveSecretFinish.IsInvalid ? null : new Secret.Value(resultRetrieveSecretFinish);
}

[Version("0.19.0")]
public Secret.Value? RetrieveSecretSync(Gio.Cancellable? cancellable)
{
    
    var resultRetrieveSecretSync = Secret.Internal.Retrievable.RetrieveSecretSync(this.Handle.DangerousGetHandle(), cancellable?.Handle.DangerousGetHandle() ?? IntPtr.Zero, out GLib.Internal.ErrorOwnedHandle error);
if(!error.IsInvalid)
    throw new GLib.GException(error);
    
    
    return resultRetrieveSecretSync.IsInvalid ? null : new Secret.Value(resultRetrieveSecretSync);
}
}