
using System;
using System.Linq;
using GObject;
using System.Runtime.InteropServices;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY

public partial class RetrievableHelper : GObject.GTypeProvider
{
    

public static new GObject.Type GetGType()
{
    
    var resultGetGType = Secret.Internal.Retrievable.GetGType();

    
    
    return resultGetGType;
}

    
}