
using System;
using GObject;
using GObject.Internal;
using System.Runtime.InteropServices;

#nullable enable

namespace Secret
{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial interface Retrievable
    {
        ObjectHandle Handle { get; }
        
        public static readonly Property<GLib.HashTable, Retrievable> AttributesPropertyDefinition = new (
    unmanagedName: "attributes",
    managedName: nameof(Attributes)
);

public GLib.HashTable Attributes { get; set; }

public static readonly Property<ulong, Retrievable> CreatedPropertyDefinition = new (
    unmanagedName: "created",
    managedName: nameof(Created)
);

public ulong Created { get; set; }

public static readonly Property<string?, Retrievable> LabelPropertyDefinition = new (
    unmanagedName: "label",
    managedName: nameof(Label)
);

public string? Label { get; set; }

public static readonly Property<ulong, Retrievable> ModifiedPropertyDefinition = new (
    unmanagedName: "modified",
    managedName: nameof(Modified)
);

public ulong Modified { get; set; }

    }
}