
using System;
using GObject;
using System.Runtime.InteropServices;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY

public partial interface Retrievable : IDisposable
{
    
[Version("0.19.0")]
GLib.HashTable GetAttributes();

[Version("0.19.0")]
ulong GetCreated();

[Version("0.19.0")]
string GetLabel();

[Version("0.19.0")]
ulong GetModified();


[Version("0.19.0")]
Secret.Value? RetrieveSecretFinish(Gio.AsyncResult result);

[Version("0.19.0")]
Secret.Value? RetrieveSecretSync(Gio.Cancellable? cancellable);
}