
using System;
using GObject;
using System.Runtime.InteropServices;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY

public partial class RetrievableHelper
{
    public GLib.HashTable Attributes
{
    get => Secret.Retrievable.AttributesPropertyDefinition.Get(this);
    set => Secret.Retrievable.AttributesPropertyDefinition.Set(this, value);
}


public ulong Created
{
    get => Secret.Internal.Retrievable.GetCreated(Handle.DangerousGetHandle());
    set => Secret.Retrievable.CreatedPropertyDefinition.Set(this, value);
}


public string? Label
{
    get => Secret.Retrievable.LabelPropertyDefinition.Get(this);
    set => Secret.Retrievable.LabelPropertyDefinition.Set(this, value);
}


public ulong Modified
{
    get => Secret.Internal.Retrievable.GetModified(Handle.DangerousGetHandle());
    set => Secret.Retrievable.ModifiedPropertyDefinition.Set(this, value);
}


}