
using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY


public sealed partial class RetrievableHelper : GObject.Object, Retrievable, GObject.InstanceFactory
{
    public RetrievableHelper(GObject.Internal.ObjectHandle handle) : base(handle)
    {
    }

    static object GObject.InstanceFactory.Create(IntPtr handle, bool ownsHandle)
    {
        return new RetrievableHelper(new GObject.Internal.ObjectHandle(handle, ownsHandle));
    }
}