
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY


[Flags]
public enum SchemaFlags : uint
{
    None = 0,
DontMatchName = 2,
}