
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY


public enum SchemaType : int
{
    Note = 0,
CompatNetwork = 1,
}