
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY


public enum SchemaAttributeType : int
{
    String = 0,
Integer = 1,
Boolean = 2,
}