
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY


public sealed partial class Schema : GLib.BoxedRecord, GObject.GTypeProvider, GObject.InstanceFactory, IEquatable<Schema>, IDisposable
{
    public Secret.Internal.SchemaOwnedHandle Handle { get; }

    public Schema(Secret.Internal.SchemaOwnedHandle handle)
    {
        Handle = handle;
    }

    public Schema() : this(Secret.Internal.SchemaManagedHandle.Create())
    {
    }

    static object GObject.InstanceFactory.Create(IntPtr handle, bool ownsHandle)
    {
        var safeHandle = ownsHandle
            ? new Secret.Internal.SchemaOwnedHandle(handle)
            : Secret.Internal.SchemaOwnedHandle.FromUnowned(handle);

        return new Schema(safeHandle);
    }

    


public static Schema New(string name, Secret.SchemaFlags flags, GLib.HashTable attributeNamesAndTypes)
{
    using var nameNative = GLib.Internal.NonNullableUtf8StringOwnedHandle.Create(name);
    var schemaHandle = Internal.Schema.New(nameNative, flags, attributeNamesAndTypes.Handle);
return new Schema(schemaHandle);

}

    public static GObject.Type GetGType()
    {
        return Secret.Internal.Schema.GetGType();
    }

    public string? Name {
get => Marshal.PtrToStringUTF8(Handle.GetName());
set => Handle.SetName(GLib.Internal.StringHelper.StringToPtrUtf8(value));
}

public Secret.SchemaFlags Flags {
get => Handle.GetFlags();
set => Handle.SetFlags(value);
}











    

    

public Secret.Schema Ref()
{
    
    var resultRef = Secret.Internal.Schema.Ref(this.Handle);

    
    
    return new Secret.Schema(resultRef);
}


public void Unref()
{
    
    Secret.Internal.Schema.Unref(this.Handle);

    
    
    
}

    System.IntPtr GLib.BoxedRecord.GetHandle()
    {
        return Handle.DangerousGetHandle();
    }

    public bool Equals(Schema? other)
    {
        if (ReferenceEquals(null, other))
            return false;

        if (ReferenceEquals(this, other))
            return true;

        return Handle.Equals(other.Handle);
    }

    public override bool Equals(object? obj)
    {
        return ReferenceEquals(this, obj) || obj is Schema other && Equals(other);
    }

    public override int GetHashCode()
    {
        return Handle.GetHashCode();
    }

    partial void OnDispose();

    public void Dispose()
    {
        OnDispose();
        Handle.Dispose();
    }
}