
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY


[Flags]
public enum SearchFlags : uint
{
    None = 0,
All = 2,
Unlock = 4,
LoadSecrets = 8,
}