
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY


[Flags]
public enum ServiceFlags : uint
{
    None = 0,
OpenSession = 2,
LoadCollections = 4,
}