
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY


public sealed partial class ServiceClass
{
    public Secret.Internal.ServiceClassOwnedHandle Handle { get; }

    public ServiceClass(Secret.Internal.ServiceClassOwnedHandle handle)
    {
        Handle = handle;
    }

    public ServiceClass() : this(Secret.Internal.ServiceClassOwnedHandle.Create())
    {
    }

    

    









    

    

    public bool Equals(ServiceClass? other)
    {
        if (ReferenceEquals(null, other))
            return false;

        if (ReferenceEquals(this, other))
            return true;

        return Handle.Equals(other.Handle);
    }

    public override bool Equals(object? obj)
    {
        return ReferenceEquals(this, obj) || obj is ServiceClass other && Equals(other);
    }

    public override int GetHashCode()
    {
        return Handle.GetHashCode();
    }
}