
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY


[GObject.Handle<Secret.Internal.ServiceHandle>]
public partial class Service(Secret.Internal.ServiceHandle handle) : Gio.DBusProxy(handle), Gio.AsyncInitable, Gio.DBusInterface, Gio.Initable, Secret.Backend
{
       public Service(params GObject.ConstructArgument[] constructArguments) : this(Secret.Internal.ServiceHandle.For<Service>(constructArguments)) { }
}