
namespace Secret;

// AUTOGENERATED FILE - DO NOT MODIFY

public class VersionAttribute : System.Attribute
{
    public string Version { get; }

    public VersionAttribute(string version)
    {
        Version = version;
    }
}